# Beth's guide to Integration by Parts

Background: We are now at a point where the author of this section feels obliged to ["break the fourth wall"](https://en.wikipedia.org/wiki/Fourth_wall) and to communicate with the reader about decisions on whether or not to include topics in a textbook.

Many readers will incline to believe that the contents of a textbook reflect the logical and factual structure of the topic and that any material included in the book bears substantially on the reader's ability to make good use of the overall subject. In reality, some topics appear in a textbook not because they are directly of essential use but simply because they have appeared uncritically in previous textbooks and therefore are part of the way the instructor thinks about the instructor. In the author's personal view, we are now about to engage one such topic.

You will have already memorized the anti-derivatives of almost all of the pattern-book functions---the exceptions are the natural logarithm and the sigmoid. And you should be able to step through the simple logic of a basic modeling function, that is, a linearly parameterized extension of a pattern-book function, like $A \cos(\omega t)$ whose anti-derivative (with respect to $t$) is $\frac{A}{\omega}\sin(\omega 5)$. 

But every function has an anti-derivative. For some functions whose formulas expressed in algebraic notation, it is impossible to write the anti-derivative in algebraic notation (but there are other ways to implement it). For some functions, such as $\ln(t)$, there is a simple formula: $\int \ln(t) dt = t\left[\strut \ln(t) - 1\right]$. To the reader meeting that formula for the first time, it must seem to have come from out of the blue. But you don't need to accept my word; derivatives are easy and you can calculate $\partial_t\, t \left[\strut \ln(t) - 1\right]$ with the product rule and your knowledge of the pattern-book functions.
$$\partial_t \left[t \left[\strut \ln(t) - 1\right]\right]
= \left[\strut\ln(t) - 1 \right] + t \frac{1}{t} = \ln(t)$$

Confirming such a formula when given is one thing; figuring out the formula from scratch is quite another thing. Identifying which functions have anti-derivatives that can be written algebraically, and finding the right formula, is a genuinely intellectual challenge. Much like solving Sudoku, the challenge can be overcome by some combination of natural talent, experience, recognition of previously encountered patterns, and an attitude of persistence. The successful solver of anti-differentiation puzzles will draw on all of these. 

By tradition, calculus students are introduced to a small set of "techniques" for anti-differentiation; ways to look at a function, see a pattern, and exercise the anti-differentiation rule appropriate for that pattern.

I've looked at textbooks spanning more than a century. The same few examples are given in almost all books. From this evidence, I conclude that it is not necessary to master the anti-differentiation rules; you are unlikely to get any further than did 100 years of textbooks. It suffices to memorize a few of the functions, much as you may have memorized a few of the titles of Shakespeare's plays. Such knowledge enables you to "pass" in conversations about mathematics. Of legitimate utility is to know how to look up anti-derivatives of functions in a reference book or application and to master differentiation well enough that you can confirm or reject a candidate formula.



## Where the formula comes from

$\partial(u \cdot v) = \partial u \cdot v + u \cdot \partial v$

## How to use the formula

$$\underbrace{\int x \cos(x) dx}_{\int u dv} $$

1. Pick $u$ (easy to differentiate)
2. Pick $v$ (easy to anti-differentiate)

So we'll chose $u = x$ and $dv = \cos(x) dx$

Giving $du = dx$ and $v = \sin(x)$

