# Glossary

Pattern book functions (Functions)

Discrete (Functions) see continuous

Continuous (Functions) 

Discontinuous (Functions)

Smooth (Functions)

Curvature (Derivatives)

Line fitting (Functions & Linear Algebra)

Apply a function (Functions)

Graphics frame (Graphics)

Pipeline (Computing)

Inverse (Functions)

Zero-finding (Operations) see solving

Differentiation (Operations)

Integration (Operations)

Iteration (Operations)

Machine learning (Functions)

Contour plot (Graphics)

Slice plot (Graphics)

Graph (in the technical sense) (Graphics)
Slope (Functions)

Parameter (Functions)

Baseline (Functions) as in an exponential function

Offset (Functions) as in an exponential or sinusoid

Amplitude (Functions) as in a sinusoid

Linear combination (Functions) see also (Vectors)

Scalar (Functions)

Coefficient (Functions)

Tilde expression (Computing)

Domain (Functions), see also graphics domain, versus range

Range (Functions)

Concavity (Functions), see also derivatives, concave up, concave down

Inflection point (Functions), see concavity

Periodic (Functions) 

Cycle (Functions) see periodic

Asymptote (Functions), vertical and horizontal

Argmax (Optimization) also argmin

Maximum (Optimization) versus argmax

Optimization (Optimization)

Local maximum (Optimization) also local minimum

Global maximum (Optimization) versus local maximum

Functional notation (Notation)

Infix notation (Notation)

Slope function (Derivatives)

Formula (Functions) not the same as equation

Equation (Functions) versus definition

Doubling time (Functions) see half-life

Half-life (Functions) see doubling-time

Input (Functions)

Output (Functions)

Variable, reserve for statistics and dynamical system, don't use as synonym for "unknown"

Number (Dimension) versus quantity

Unit (Dimension)

Dimension (Dimension), see also vector space 

Interpolation (Functions)

Interpolating function (Functions)

Knots (Functions) see spline

Spline (Functions) see interpolation

Cubic spline (Functions) see interpolation

Bézier Spline (Functions) see interpolation

Control point (Functions) see Bézier spline

Fourier transform (Functions) see linear combination, sinusoids

Dot product (Vectors)

Matrix (Vectors) also, multiplication 

Target problem (Vectors) and target vector

Model space (Vectors)

Mutually orthogonal (Vectors)

Modeling cycle (Modeling)

Response variable (Modeling)

Explanatory variable (Modeling)


Subspace (Vectors) see span

Projection (Vectors)

Residual (Vectors)

Model vector (Vectors)

QR solving (Vectors)


Harmonic (Vectors)

Time domain (Vectors)

Frequency domain (Vectors)

Span (Vectors)

Assignment (Computing)

Argument (Computing, Functions), see input

Logarithmic scale (Graphics) 

Decade (Graphics) see logarithmic scale

Bit (Logarithm) the unit of the base-2 logarithm

Power-law function (Functions)

Identity function (Functions), see proportional function and linear combination

Constant function (Functions)

Semi-log (Graphics) see logarithmic scale

Log-log (Graphics) see logarithmic scale

Guess and check (Operations) see algorithms, iteration

Iteration (Operations)

Constraint (Optimization) 

Present value (Application) also net present value

Discounting (Application)

Vector valued function (Functions)

Finite

Infinitesimal (Derivatives) see limits

Equilibrium (Dynamics)

Work (applications) see force, distance

Decompose a vector (Vectors) see vector decomposition

Vector decomposition (Vectors)

Conserved quantity (Applications) energy, momentum, in dynamics chapter

Potential energy (Applications)

Kinetic energy (Applications)

Torque (Applications)

Angular velocity and acceleration (Applications)

Newton step (Operations) see solving and optimization

Budget constraint (Optimization) see constraint

Incomensurate (Dimension) see also optimization and constraint

Lagrange multiplier (Optimization) see constraint

Shadow price (Optimization) see Lagrange multiplier

Uncertainty (Probability)

Probability (Probability)

Likelihood function (Probability)

Distribution (Probability)

Density function (Probability)

Prior density function (Probability)

Posterior density function (Probability)

Relative density function (Probability)

Normalizing (Probability) see relative density 

Expected value (Probability)

Center of mass (Applications)

Moment of inertia (Applications)

Variance (Probability) see standard deviation

Bayes' rule and Bayesian inference (Probability)

Function fitting (Functions)

Single-valued (Functions)

Maximum likelihood estimation (Probability), see likelihood function

Standard deviation (Functions) parameter for gaussian and sigmoid, see also center and spread

Mean (Functions) parameter for gaussian and sigmoid, see also center and spread

Center and spread (Functions) see also Gaussian

Gaussian (Functions)

Sigmoid (Functions)

Sinusoid (Functions)

Function multiplication (Functions)

Function composition (Functions)

Bilinear (Polynomials) see interaction term

Quadratic term (Polynomials)

Order of magnitude (Dimension) see logarithm

Natural logarithm (Functions) see logarithm, base-10, base-2

Cumulative (Probability)

Cumulative sum (Accumulation)

Accumulation (Accumulation)

Anti-differentiation (Accumulation)

Integration (Accumulation)

Net change (Accumulation)

Definite integral (Accumulation) compare indefinite integral

Indefinite integral (Accumulation) see anti-derivative

Bound of integration (Accumulation) lower and upper, left and right

Dummy variable (Accumulation)

Fundamental theorem of calculus, first and second

Euler method (Accumulation)

Euler method (Dynamics)

Symbolic derivative, anti-derivative 

Techniques of integration (Accumulation)

U-substitution (Accumulation) see techniques of integration

Integration by parts (Accumulation) see techniques of integration

Algorithm (Functions) and (Operations)

Linear interpolation (Functions) see interpolation

Low-order polynomial (Polynomial)

Order (General) see polynomial, dynamics

With-respect-to-input (Derivatives)

Rate of change, instantaneous (Derivatives), vs average rate of change

Chain rule (Derivatives) see function composition

Product rule (Derivatives) see function multiplication

Sum rule (Derivatives) see linear combination

Second derivative (Derivatives)

Third derivative (Derivatives) and so on

Interior function (Functions) see composition

Exterior function (Functions) see composition

Power-law rule (Derivatives)

Partial derivative (Derivatives) hold constant

Normal (Functions) see Gaussian

Normal (Vectors) see orthogonal

Orthogonal (Vectors)

Correlation coefficient (Vectors)

Coefficient of variation (Vectors) see R-squared

R-squared (Vectors)

Orientation (Vectors)

Linear algebra (Vectors)

Embedded (Vectors)

Degrees of freedom (Vectors)

Componentwise (Vectors)

Intercept vector (Modeling)

Variation (Modeling)

Data frame (Modeling) 

Objectives (Optimization)

Euler's constant (Functions)
Piecewise  (Functions)

Heaviside function (Functions)

Ramp function (Functions)

C^0^, C^1^, C^2^, ... C-infinity (Derivatives) see continuity

Linear operator (Operations) see differentiation, anti-differentiation

Constant of integration (Accumulation)

Differencing operator (Operations)

Transient (Dynamics)

Fundamental dimension (Dimension) Length, time, mass

Compound dimension (Dimension) area, volume, velocity, momentum, acceleration, force, energy, power

Density (Dimension)

Flavors of 1 (Dimension)

Input scaling (Functions)

Output scaling (Functions) see linear combination

Finite-difference (Differentiation)

Differentiation (Differentiation)

Limit (Differentiation)

Evanescent h (Differentiation)

Instant (Differentiation)

Newton's Second Law of motion (Dynamics), see acceleration

Acceleration (Differentiation)

Basic model of change (Functions) $\line(x) \equiv a x + b$

Operator, function (Computing)

Newton's Law of Cooling (Dynamics)

Objective function (Optimization)

Framework: (Dynamics)

Differential equations (Dynamics)

Interest rate (Applications) see exponential growth, discount rate

Decay (Functions) see exponential

Linear stable model (Dynamics)

Linear unstable model (Dynamics)

Bounded stable model (Dynamics)

Curve () see path, see surface, see parameterized surface.

Tangent plane (), see parameterized surface

Orientation

Radioactive decay (Dynamics)

Chain reaction (Dynamics) and exponential growth, explosion

Coupling (Dynamics)

Phase plane (Dynamics) see State space

State space (Dynamics)

State, instantaneous (Dynamics)

Interaction term (Dynamics) see interaction, low-order polynomials in two variables

SIR model (Dynamics)

Predator-prey model (Dynamics)

Fixed point (Dynamics)

Stability (Dynamics)

Saddle (Dynamics)

Flow field (Dynamics) see vector field

Linear approximation (Dynamics)

Tipping point (Dynamics)

Bifurcation (Dynamics)

Catastrophe (Dynamics)

Carrying capacity (Dynamics)

Exponential growth (Dynamics)

Dynamical system (Dynamics)

Second-order differential equation (Dynamics)

First-order differential equation (Dynamics)

Discrete-state (Dynamics) vs Continuous-state

Discrete-time (Dynamics) vs Continuous-time (which is needed for a continuous-state system)

Trajectory (Dynamics)

Oscillatory (Dynamics)

Eigenvalue (Dynamics)

Eigenvector (Dynamics)

Chaos (Dynamics)

Dynamical function (Dynamics)

Solution (Dynamics)

Time series (Dynamics)

Vector (Linear combinations) applications: flow in dynamical system, gradient field

State velocity (Dynamics)

Stochastic (Dynamics)

Determistic (Dynamics)

Transient (Dynamics)

Force-balance equation (Dynamics)

Ballistics (Dynamics)

Complex number (Dynamics), imaginary number

Damping (Dynamics) air resistance

Ansatz (Dynamics)

Gradient ascent (Optimization) or descent

Gradient field (Derivatives) see vector field

Gradient vector (Derivatives)

Total derivative (Derivatives)

Taylor polynomial (Polynomials)

Factorial (Polynomials) see Taylor polynomial

Production function (Applications)

Demand function (Applications)
