# Introduction {- #block4-intro .nonumber}

In Blocks 1 through 3, you learned how to formulate calculus questions in terms of ***functions*** and the two main operations of calculus, ***differentiation*** and ***anti-differentiation***, which transform one function into another. You also learned the primary use of anti-differentiation, to accumulate the output of a function over an interval of the input variable.

There is more mathematics yet to come. In Block 5 you'll meet a major technique for modeling used in essentially all quantitative disciplines and with particularly important applications to data science. In Block 6 we'll start to work with multi-component systems as they evolve in time.

Here, in Block 4, we're going to step momentarily away from the introduction of new mathematical concepts. Functions, differentiation, and anti-differentiation are impressive and useful in their own right so now we're going to look at how they are used, how they manifest themselves in diverse ways in the world of science and technology. Our emphasis will not be on field-specific applications, although there are many! Instead, we'll explore ways the concepts of calculus appear and are used broadly in quantitative work.
