## Hopeful derivatives

[This article](https://www.economist.com/node/13145616/print?story_id=13145616) appeared in *The Economist* 10 years ago.

> **America's economy: The second derivative may be turning positive**

*When the going gets tough, the tough get their maths books out*

MANY of the diehard optimists on Wall Street have been beaten to a pulp by now, but those still standing have fallen back on a nifty bit of calculus. The second derivative, they say, is turning positive. That means that although the economy is spiralling down, it is doing so more slowly.

There are a few bits of data to back up this assertion. Retail sales rose by 1% in January from December, the first monthly increase since June. Car sales fell in January but were stable to individual buyers, if not to corporate fleets. The economy may shrink at a slightly lower rate in the first quarter than it did in the fourth (in part because fourth-quarter growth is likely to be revised to a steeper drop than the first annualised estimate of 3.8%). An index compiled by JPMorgan Chase finds that although economic news remains on balance worse than expected, the margin of awfulness has shrunk a bit; the firm's analysts have marginally trimmed the risk of “a mini-depression”.

Meanwhile, thanks to huge policy stimulus by the authorities since October, yields on corporate bonds have edged lower, interbank rates have improved, and the money supply has surged. Thomson Reuters, a data gatherer, says that more than $100 billion of American corporate bonds have been issued this year, more than the four preceding months combined (though many are federally guaranteed).

Larry Hatheway, a strategist at UBS, says a shift in the data from uniformly bad to mixed normally suggests that demand and production are coming back into balance. However, “This isn't a normal cycle,” he notes. Credit supply has not remotely returned to normal; he points out that investment-grade companies are still borrowing at a punitive 8% even after recent improvements in the market. Though a few junk-bond issuers have tapped the market, part of the demand may have come from funds “gambling for resurrection”, ie, taking a big risk for high yields in a desperate bid to offset losses elsewhere.

For each scrap of good news, there is plenty of the bad stuff. A 16.8% plunge in housing starts in January suggests no bottom is in sight there. Except for Chinese credit (see article), there is little encouraging in the rest of the world. What optimism the markets have shown has been mostly down to hopes of effective policy. This week's equity rout suggests that policymakers still struggle to meet those expectations.

See questions at <http://www.mosaic-web.org/go/Repository/SommerGentry/secondDerivativeInTheNews.pdf>

[from  Sommer Gentry]

1. Complete these sentences according to the
information in the article.

    - The ___________ (value, first derivative, second derivative) of retail sales is ________________(positive, negative).
    - The __________ (value, first derivative, second derivative) of car sales is ____________(positive, negative).
    - The _____________ (value, first derivative, second derivative) of the economy is ___________________(positive, negative).
    - The _____________ (value, first derivative, second derivative) of JP Morgan's estimate of the risk of a mini-depression is ____________(positive, negative).

2. The first paragraph of the article contains a description of "the second derivative ... turning positive." Explain why you do or do not think the description is accurate.

3. The second paragraph of the article claims to contain a few bits of data to back up the assertion mentioned in 2. Each of the next four sentences of the second paragraph evaluates an economic indicator. Only two of these sentences actually give data that show the second derivative of an economic indicator is positive. Which two indicators: retail sales, car sales, the economy, or the risk of a minidepression as estimated by JP Morgan Chase?

4. What is the difference between the phrase, "the second derivative is turning positive" and an alternative phrase, "the second derivative is positive"?

5. What effects do you think imprecise language about mathematics in the popular press will have on students studying calculus?

6. What effects might imprecise language have on non-technical consumers of news?

7. What effects might imprecise language have on mathematically savvy economists and policy makers who read this news?

