# Dynamics {#dynamics-draft}

1. Introduction to dynamics
    a. Objectives/topics: 
        i. Explain the format in which we present dynamics as opposed to trajectories
        i. Find qualitative solutions from an initial condition
        i. Articulate the difference between state, dynamics, and trajectory
2. May’s Cows
    a. Objectives/topics
        i. Classify fixed points as stable/unstable given the dynamics
        i. Identify the dynamics of constant growth
        i. Compute Euler solutions (format for expressing the system and the format of the result)
        i. Analyze models in application contexts (for example May’s Cows - a model of bistability in ecology)
3. Linearization
    a. Objectives/topics
        i. Linear expansion around a fixed point 
        i. Qualitative solution to exponential growth
        i. Understand that growth involves exponentials
        i. Impulse response and convolution (?)
        i. Bang/bang control theory (?)
4. Systems of nonlinear differential equations
    a. Objectives/topics
        i. Understand the format of presentations of dynamics (vector fields) and trajectories ( x vs t, y         i. vs t or phase plane)
        i. Finding solutions graphically (flow fields)
        i. Dependence on initial condition
5. Models leading to flow fields
    a. Objectives/topics
        i. Apply modeling techniques (from block 2) local low order polynomials
        i. Predatory/Prey (flow fields and the phenomena of the trajectories)
        i. SIR (flow fields and the phenomena of the trajectories)
        i. The differences between these two models
6. Additional models and flow fields (catch up day)
    a. Objectives/topics
        i. (Richardson’s arms race model and conflict model, action potentials) Numerics, look at the trajectories 
        i. Exercise: `insert_calcZ_exercise("XX.XX", "iRZfBY", "Exercises/walnut-tell-pot.Rmd")`
        i. Analysis of phase plane with nullclines
7. Fixed points of nonlinear systems in the phase plane 
    a. Objectives/topics
        i. Determine fixed points and linearize the system around the fixed points
        i. Flow field of the linear approximation
        i. Matrix representation of the flow field
        i. Iteration of matrices
        
        

8. Eigenvalue/Eigenvector analysis
    a. Objectives/topics
        i. Understand the geometry of the flow (what an eigenvector looks like in terms of the flow, as it emerges from the image of the flow field)
        i. Trajectories as linear combinations of eigenflows
        i. Classification of fixed points
9. Calculus of second order differential equations
    a. Objectives/topics
        i. Force balance equations
        i. Equivalence to phase plane description
        i. Exponential Ansatz (solution is made up of exponentials, which one?)
        i. Complex eigenvalues
10. Harmonic Oscillator 
    a. Objectives/topics
        i. Complex exponentials and their equivalency to sinusoids 
        i. Sinusoids with exponential amplitudes (damping)
        i. Relation to the real and complex parts of the eigenvalues
        i. Forcing and resonance
11. Brownian motion (see chapter in Block 4 directory)



Example: In Chapter FUTURE-VALUE we examined the problem of determining the rate of payback for a loan of amount ${\cal P}_0$ extending over 30 months at an interest rate $r$. We determined the rate of repayment $A$ (in dollars per month) by discounting future payments and accumulating the present value of the payment stream over the duration of the loan. The mathematics were

$$\int_0^{30} A e^{-kt} \, dt = {\cal P}_0$$ where $k = \ln(1+r)$.

Let's return to the problem from the perspective of dynamical systems. The state quantity will be the principal yet to be repaid: ${\cal P}(t)$. At $t=0$ this is the amount of the loan, ${\cal P}_0$. The principal grows at a rate of $r$ per month. Countering this is the repayment of the loan at the rate $A$ per month. Taken together, the time rate of change of the principal is
$$\partial_t {\cal P}(t) = r {\cal P}(t) - A\ .$$
To figure out the proper amount of payment $A$, we can solve this differential equation subject to the initial condition ${\cal P}(0) = {\cal P}$ and the terminating condition $P(30) = 0$. 

As usual, we find the fixed point of the dynamics:$$\partial_t{\cal P}(t) = 0 = r {\cal P}(t) - A$$ and replace $P(t)$ by a shifted quantity $y(t)$ that is zero at the fixed point: $y(t) = {\cal P}(t) - A/r$. The dynamics of $y(t)$ are exponentialgrowth : $\partial_t y(t) = r y(t)$ and have a solution $y(t) = y(0) exp^{r t}$. Translating this back into terms of ${\cal P}()$, the solution is $${\cal P}(t) - \frac{A}{r} = \left[\strut {\cal P}_0 - \frac{A}{r}\right] e^{rt} \ \ \implies\ \  P(t) = \left[\strut {\cal P}_0 - \frac{A}{r}\right] e^{rt} + \frac{A}{r}\ .$$ 

We now seek to find the amount $A$ that will give ${\cal P}(t) = 0$. This is, of course, a zero-finding problem. [SEE EXERCISE (to be written) where we'll ask to solve it both symbolically and with `findZeros()`] The answer we'll get is $443.27 per month, which is slightly different from the amount we got in Chapter future value, which was 442.09. I DO NOT KNOW WHERE THE DIFFERENCE COMES FROM. NEED TO FIGURE IT OUT.


