# Eigenvalues, eigenvectors {#eigenvalues}

::: {.underconstruction}
8. Eigenvalue/Eigenvector analysis
    a. Objectives/topics
        i. Understand the geometry of the flow (what an eigenvector looks like in terms of the flow, as it emerges from the image of the flow field)
        i. Trajectories as linear combinations of eigenflows
::: 


In the previous chapters, you've seen how linear dynamics, when unstable, lead trajectories off to infinity. Chapter \@ref(modeling-dynamics) looked at some ways that nonlinearity can tame instability, as in the simple models of linear growth.

In this chapter, we return to linear dynamics to develop a *quantitative theory of stability*. Such theory is important in many engineering and design applications. For instance, a building exposed to earthquake risk can be economically designed to be strong specifically against the type of shaking produced by earthquakes. An electronic circuit can be designed to be sensitive to certain kinds of communication signals while still resisting noise or jamming.

::: {.example data-latex=""}
***Cruise control*** is a feature of many modern automobiles. It enables a driver to set a desired speed for the car to follow automatically, thus reducing cognitive load on the driver.
Early models of cruise control introduced in the 1970s (and still common in 2020) had an extremely simple logic. The speedometer constantly monitors the car's speed $v$. The driver sets a desired speed, which we'll call $v_0$. The cruise control actuator---the mechanism that works to maintain the speed at $v_0$ by, let's say, adjusting the throttle to increase or reduce speed as appropriate---is designed to produce a throttle input proportional to the deviation in actual speed $v$ from the set speed $v_0$.
$$\text{throttle_input} = -a (v - v_0)\ .$$
You can see that when $v = v_0$, the throttle input from the system is zero. When $v_0 < v$, as when starting to go downhill, the throttle input will be negative, reducing the speed. 

A simple model is that the throttle input is proportional to $\partial_t\, v$: positive input increases speed, negative input decreases speed. The overall system is then described by a linear, first-order differential equation $$\partial_t\,v = -a(v-v_0)\ .$$ This equation has a fixed point at $v = v_0$ (as desired) and is stable: a deviation from $v_0$ will be followed by exponential decay back to $v_0$. 

EXERCISE, SOLVE THIS EQUATION

A modern cruise control system adds an important feature: the car slows down automatically if it gets too close to the car in front. Let's call the distance to the leading car $x$ and define "too close" to mean closer than distance $x_0$. The control system looks like this:
$$\partial_t v = \left\{\begin{array}{l}- a (v-v_0) \ \text{if}\ x_0 < x\\
-b(x-x_0) \ \text{otherwise}\end{array}\right.$$
For a system to work, the dynamics must be stable. But the signs are not good. For instance, when in car-following mode, the dynamics are $$\partial_t v \equiv \partial_{tt} x = - b(x-x_0)\ .$$
This system will show sinusoidal oscillations around the fixed point $x=x_0$. To see why, define $y=x-x_0$. Re-written in terms of $y$, the differential equation is $\partial_{tt} y = -b y$ which has a solution $y=A \sin\left(\sqrt{b} \ t\right)$.
:::


Show that starting on an eigenvector stays on an eigenvector. The time series will be either a growing exponential or a decaying exponential, depending on the sign of $\lambda$.

Every $n\times n$ matrix---we are working with $2\times 2$ matrices for simplicity--has associated with it a set of $n$ numbers called *eigenvalues*.  This is a mix of the German word "eigen" meaning "characteristic," and the English work "values." Sometime they are called *characteristic values* just to render them purely in English. But "eigen" has a single, specific meaning in mathematics, so the word "eigenvalue" is more evocative to mathematicians than is "characteristic values."

The letter used to represent eigenvalues is the Greek lambda: $\lambda$. Since our $2\times 2$ matrices have 2 eigenvalues, we often write the pair as $\lambda_1$ and $\lambda_2$ or even as $\lambda_{1,2}$. 

For an [ab10] matrix, the formula for the eigenvalues is

$$\lambda_{1,2} = \frac{1}{2} \left[a \pm \sqrt{a^2 + 4b\strut}\right]$$

Note the use of the $\pm$ in the formula. The same formula gives *both* eigenvalues, one from the $+$ branch of the $\pm$, the other from the $-$ branch. Using the $\pm$ rather than two different formulas---one with $-$ and one with $+$---is merely a convenience to make it explicit what the two formulas would have in common.

Writing $\lambda_{1,2}$ is nothing more than saying $\lambda_1$ *and* $\lambda_2$.

## Exercises

`r insert_calcZ_exercise("XX.XX", "OwCtGH", "Exercises/child-buy-drawer.Rmd")`

`r insert_calcZ_exercise("XX.XX", "Rdc7vE", "Exercises/beech-ride-bowl.Rmd")`

`r insert_calcZ_exercise("XX.XX", "PD3CiZ", "Exercises/panda-teach-door.Rmd")`



EXERCISES: Give numbers for $abcd$ and $x(0)$ and $\partial_t x(0)$. Find the eigenvalues and $A$ and $B$.
