<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 53 Eigenvalues, eigenvectors | MOSAIC-Calculus.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.24.1 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 53 Eigenvalues, eigenvectors | MOSAIC-Calculus.knit" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 53 Eigenvalues, eigenvectors | MOSAIC-Calculus.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="equilibria.html"/>
<link rel="next" href="second-order-de.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<span class="math inline">
\(\newcommand{\line}{\text{line}}
\newcommand{\hump}{\text{hump}}
\newcommand{\sigmoid}{\text{sigmoid}}
\newcommand{\recip}{\text{recip}}
\newcommand{\diff}[1]{{\cal D}_#1}
\newcommand{\pnorm}{\text{pnorm}}
\newcommand{\dnorm}{\text{dnorm}}
\let\origvec\vec
\let\origmathit\mathit
\let\orighat\hat
\let\origbar\bar
\newcommand{\vec}[1]{\overset{{\rule[-1pt]{0mm}{1mm}}\rightharpoonup}{\mathbf{#1}}}
\newcommand{\bar}[1]{\overset{{\rule[-1pt]{12pt}{.5mm}}}{\mathbf{#1}}}
\newcommand{\mathit}[1]{\underset{\leftharpoondown}{\overset{{\rightharpoonup}}{\large\mathbf #1}}}
\newcommand{\hat}[1]{\widehat{\ \mathbf#1\ }}
\newcommand{\len}[1]{{\|{\mathbf #1}\|}}
\newcommand{\tvec}[1]{\overset{\uparrow}{\mathbf #1}}
\newcommand{\tmat}[1]{\overset{\leftrightarrows}{\mathbf #1}}
\newcommand{\perpendicularto}[2]{#1\!\perp\!#2}
\newcommand{\modeledby}[2]{#1\!\sim\!#2}
\newcommand{\CC}[1]{\color{#648fff}{#1}}
\newcommand{\CE}[1]{\color{#785ef0}{#1}}
\newcommand{\CA}[1]{\color{#dc267f}{#1}}
\newcommand{\CB}[1]{\color{#fe6100}{#1}}
\newcommand{\CD}[1]{\color{#ffb000}{#1}}\)
</span>



<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="mosaic-calc-style-copy.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="../docs/welcome-to-calculus.html">Welcome to calculus</li>
<li><a href="../block-1/change.html">Block 1: Functions & quantities</a></li>
<li><a href="../block-2/change-relationships.html">Block 2: Differentiation</a></li>
<li><a href="../block-3/change-accumulation.html">Block 3: Accumulation</a></li>
<li><a href="../block-4/block4-intro.html">Block 4: Manifestations</a></li>
<li><a href="../block-5/vectors.html">Block 5: Linear combinations</a></li>
<hr>
<li><strong><a href="../block-6/diff-eq-intro.html">Block 6: Dynamics</a></strong></li>

<li class="divider"></li>
<li class="chapter" data-level="47" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html"><i class="fa fa-check"></i><b>47</b> Differential equations</a>
<ul>
<li class="chapter" data-level="47.1" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#dynamical-systems"><i class="fa fa-check"></i><b>47.1</b> Dynamical systems</a></li>
<li class="chapter" data-level="47.2" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#state"><i class="fa fa-check"></i><b>47.2</b> State</a></li>
<li class="chapter" data-level="47.3" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#state-space"><i class="fa fa-check"></i><b>47.3</b> State space</a></li>
<li class="chapter" data-level="47.4" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#dynamics"><i class="fa fa-check"></i><b>47.4</b> Dynamics</a></li>
<li class="chapter" data-level="47.5" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#state-space-and-flow-field"><i class="fa fa-check"></i><b>47.5</b> State space and flow field</a></li>
<li class="chapter" data-level="47.6" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#exercises"><i class="fa fa-check"></i><b>47.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="48" data-path="solve-DE.html"><a href="solve-DE.html"><i class="fa fa-check"></i><b>48</b> Finding a “solution”</a>
<ul>
<li class="chapter" data-level="48.1" data-path="solve-DE.html"><a href="solve-DE.html#the-flow-field"><i class="fa fa-check"></i><b>48.1</b> The flow field</a></li>
<li class="chapter" data-level="48.2" data-path="solve-DE.html"><a href="solve-DE.html#euler-method"><i class="fa fa-check"></i><b>48.2</b> Euler method</a></li>
<li class="chapter" data-level="48.3" data-path="solve-DE.html"><a href="solve-DE.html#symbolic-solutions"><i class="fa fa-check"></i><b>48.3</b> Symbolic solutions</a></li>
<li class="chapter" data-level="48.4" data-path="solve-DE.html"><a href="solve-DE.html#exercises-1"><i class="fa fa-check"></i><b>48.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="49" data-path="flow-on-line.html"><a href="flow-on-line.html"><i class="fa fa-check"></i><b>49</b> Flows on the line</a>
<ul>
<li class="chapter" data-level="49.1" data-path="flow-on-line.html"><a href="flow-on-line.html#the-rules-of-the-road"><i class="fa fa-check"></i><b>49.1</b> The rules of the road</a></li>
<li class="chapter" data-level="49.2" data-path="flow-on-line.html"><a href="flow-on-line.html#linearization"><i class="fa fa-check"></i><b>49.2</b> Linearization</a></li>
<li class="chapter" data-level="49.3" data-path="flow-on-line.html"><a href="flow-on-line.html#nonlinear-on-line"><i class="fa fa-check"></i><b>49.3</b> Nonlinearity</a></li>
<li class="chapter" data-level="49.4" data-path="flow-on-line.html"><a href="flow-on-line.html#exercises-2"><i class="fa fa-check"></i><b>49.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="50" data-path="flow-on-plane.html"><a href="flow-on-plane.html"><i class="fa fa-check"></i><b>50</b> Flows on the plane</a>
<ul>
<li class="chapter" data-level="50.1" data-path="flow-on-plane.html"><a href="flow-on-plane.html#qualitative-stability"><i class="fa fa-check"></i><b>50.1</b> Generic behaviors</a></li>
<li class="chapter" data-level="50.2" data-path="flow-on-plane.html"><a href="flow-on-plane.html#linearization-1"><i class="fa fa-check"></i><b>50.2</b> Linearization</a></li>
<li class="chapter" data-level="50.3" data-path="flow-on-plane.html"><a href="flow-on-plane.html#exercises-3"><i class="fa fa-check"></i><b>50.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="51" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html"><i class="fa fa-check"></i><b>51</b> Modeling dynamics</a>
<ul>
<li class="chapter" data-level="51.1" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#a-single-state-quantity"><i class="fa fa-check"></i><b>51.1</b> A single state quantity</a></li>
<li class="chapter" data-level="51.2" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#multiple-state-quantities"><i class="fa fa-check"></i><b>51.2</b> Multiple state quantities</a></li>
<li class="chapter" data-level="51.3" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#classical-phase-plane-models"><i class="fa fa-check"></i><b>51.3</b> Classical phase-plane models</a></li>
<li class="chapter" data-level="51.4" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#epidemic"><i class="fa fa-check"></i><b>51.4</b> Epidemic</a></li>
<li class="chapter" data-level="51.5" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#exercises-4"><i class="fa fa-check"></i><b>51.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="52" data-path="equilibria.html"><a href="equilibria.html"><i class="fa fa-check"></i><b>52</b> Equilibrium and transient</a>
<ul>
<li class="chapter" data-level="52.1" data-path="equilibria.html"><a href="equilibria.html#one-state-variable"><i class="fa fa-check"></i><b>52.1</b> One state variable</a></li>
<li class="chapter" data-level="52.2" data-path="equilibria.html"><a href="equilibria.html#two-state-variables"><i class="fa fa-check"></i><b>52.2</b> Two state variables</a></li>
</ul></li>
<li class="chapter" data-level="53" data-path="eigenvalues.html"><a href="eigenvalues.html"><i class="fa fa-check"></i><b>53</b> Eigenvalues, eigenvectors</a>
<ul>
<li class="chapter" data-level="53.1" data-path="eigenvalues.html"><a href="eigenvalues.html#vector-solutions-to-linear-differential-equations"><i class="fa fa-check"></i><b>53.1</b> Vector solutions to linear differential equations</a></li>
<li class="chapter" data-level="53.2" data-path="eigenvalues.html"><a href="eigenvalues.html#eigenvectors-and-eigenvalues"><i class="fa fa-check"></i><b>53.2</b> Eigenvectors and eigenvalues</a></li>
<li class="chapter" data-level="53.3" data-path="eigenvalues.html"><a href="eigenvalues.html#exercises-5"><i class="fa fa-check"></i><b>53.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="54" data-path="second-order-de.html"><a href="second-order-de.html"><i class="fa fa-check"></i><b>54</b> Force-balance equations</a>
<ul>
<li class="chapter" data-level="54.1" data-path="second-order-de.html"><a href="second-order-de.html#ballistics"><i class="fa fa-check"></i><b>54.1</b> Ballistics</a></li>
<li class="chapter" data-level="54.2" data-path="second-order-de.html"><a href="second-order-de.html#the-harmonic-oscillator"><i class="fa fa-check"></i><b>54.2</b> The harmonic oscillator</a></li>
<li class="chapter" data-level="54.3" data-path="second-order-de.html"><a href="second-order-de.html#exponential-or-sinusoid"><i class="fa fa-check"></i><b>54.3</b> Exponential or sinusoid?</a></li>
<li class="chapter" data-level="54.4" data-path="second-order-de.html"><a href="second-order-de.html#exponentials-with-imaginary-inputs"><i class="fa fa-check"></i><b>54.4</b> Exponentials with “imaginary” inputs</a></li>
<li class="chapter" data-level="54.5" data-path="second-order-de.html"><a href="second-order-de.html#damping"><i class="fa fa-check"></i><b>54.5</b> Damping</a></li>
<li class="chapter" data-level="54.6" data-path="second-order-de.html"><a href="second-order-de.html#exercises-6"><i class="fa fa-check"></i><b>54.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="55" data-path="forcing.html"><a href="forcing.html"><i class="fa fa-check"></i><b>55</b> Forcing and resonance</a>
<ul>
<li class="chapter" data-level="55.1" data-path="forcing.html"><a href="forcing.html#car-following-dynamics"><i class="fa fa-check"></i><b>55.1</b> Car following dynamics</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="eigenvalues" class="section level1" number="7">
<h1><span class="header-section-number">Chapter 53</span> Eigenvalues, eigenvectors</h1>
<!--
8. Eigenvalue/Eigenvector analysis
    a. Objectives/topics
        i. Understand the geometry of the flow (what an eigenvector looks like in terms of the flow, as it emerges from the image of the flow field)
        i. Trajectories as linear combinations of eigenflows
-->
<p>In the previous chapters, you’ve seen how linear dynamics, when unstable, lead trajectories off to infinity. Chapter <a href="modeling-dynamics.html#modeling-dynamics">51</a> looked at some ways that nonlinearity can tame instability, as in the simple models of linear growth.</p>
<p>In this chapter, we return to linear dynamics to develop a <em>quantitative theory of stability</em>. Such theory is important in many engineering and design applications. For instance, a building exposed to earthquake risk can be economically designed to be strong specifically against the type of shaking produced by earthquakes. An electronic circuit can be designed to be sensitive to certain kinds of communication signals while still resisting noise or jamming.</p>
<div class="example">
<p><span id="exm:unlabeled-div-9" class="example"><strong>Example 53.1  </strong></span><strong><em>Cruise control</em></strong> is a feature of many modern automobiles. It enables a driver to set a desired speed for the car to follow automatically, thus reducing cognitive load on the driver.
Early models of cruise control introduced in the 1970s (and still common in 2020) had an extremely simple logic. The speedometer constantly monitors the car’s speed <span class="math inline">\(v\)</span>. The driver sets a desired speed, which we’ll call <span class="math inline">\(v_0\)</span>. The cruise control actuator—the mechanism that works to maintain the speed at <span class="math inline">\(v_0\)</span> by, let’s say, adjusting the throttle to increase or reduce speed as appropriate—is designed to produce a throttle input proportional to the deviation in actual speed <span class="math inline">\(v\)</span> from the set speed <span class="math inline">\(v_0\)</span>.
<span class="math display">\[\text{throttle_input} = -a (v - v_0)\ .\]</span>
You can see that when <span class="math inline">\(v = v_0\)</span>, the throttle input from the system is zero. When <span class="math inline">\(v_0 &lt; v\)</span>, as when starting to go downhill, the throttle input will be negative, reducing the speed.</p>
<p>A simple model is that the throttle input is proportional to <span class="math inline">\(\partial_t\, v\)</span>: positive input increases speed, negative input decreases speed. The overall system is then described by a linear, first-order differential equation <span class="math display">\[\partial_t\,v = -a(v-v_0)\ .\]</span> This equation has a fixed point at <span class="math inline">\(v = v_0\)</span> (as desired). To describe more simply the dynamics around the fixed point, we can define a new dynamical state <span class="math inline">\(y=v - v_0\)</span>. Differentiating both sides with respect to time gives <span class="math inline">\(\partial_t y = \partial_t v\)</span>, so we can re-write the original differential equation as <span class="math display">\[\partial_t y = -a y\]</span> which has a solution <span class="math inline">\(y(t) = A e^{-at}\)</span> as we’ve seen before. For any positive coefficient <span class="math inline">\(a\)</span>, the control system is stable: a deviation from <span class="math inline">\(v_0\)</span> will be followed by exponential decay back to <span class="math inline">\(v_0\)</span>.</p>
<p>A modern cruise control system adds an important feature: the car slows down automatically if it gets too close to the car in front. Let’s call the distance to the leading car <span class="math inline">\(x\)</span> and define “too close” to mean closer than distance <span class="math inline">\(x_0\)</span>. The car is travelling at velocity <span class="math inline">\(v\)</span> and the car in front at <span class="math inline">\(v_f\)</span>. If <span class="math inline">\(v_f &lt; v\)</span>, the distance between the cars gets smaller: <span class="math inline">\(\partial_t x = -(v - v_f)\)</span>. On the other hand, if <span class="math inline">\(x_0 &lt; x\)</span>, the car is far enough away that the velocity can be increased: <span class="math inline">\(\partial_t v = b(x - x_0)\)</span>. We can unite these two first-order differential equations into a single, second-order equation:
<span class="math display">\[\partial_t x = -(v - v_f) \ \ \implies\ \ \partial_{tt} x = - \partial_t v = - b(x-x_0)\]</span>
To solve this system, define <span class="math inline">\(y \equiv x - x_0\)</span>. This implies <span class="math inline">\(\partial_{tt} y = \partial_{tt} x\)</span>, so the equation describing the control system becomes <span class="math display">\[\partial_{tt} y = - b y\ .\]</span>
The solution to this is <span class="math inline">\(y(t) = A \sin\left(\sqrt{b} \ t\right)\)</span> as you can confirm by substitution.</p>
<p>Result: The simple car-following control system oscillates. That’s not a very good experience for the driver! By constructing a theory of stability, we may be able to figure out a re-design that will cause the oscillations to go away.</p>
</div>
<div id="vector-solutions-to-linear-differential-equations" class="section level2" number="7.1">
<h2><span class="header-section-number">53.1</span> Vector solutions to linear differential equations</h2>
<p>The form in which we have been writing linear differential equations in two state variables is
<span class="math display">\[\partial_t x = a x + b y\\
\partial_t y = c x + d y\]</span></p>
<p>A key part of constructing a theory of stability is finding a set of mathematical ideas that enable us to view dynamics in a simpler way. The idea we will introduce here is thinking about the state and trajectory of a differential equation in terms of <strong><em>vectors</em></strong>. We’ll work here with systems with a two-variable dynamical state, but the results apply just as well to higher dimensional states. That’s important in applied work, where the systems being modeled are complicated with many state components.</p>
<p>We can re-write the linear differential equation using vector and matrix notation. Suppose that we collect the <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> components of the state into a vector, <span class="math display">\[\vec{w(t)} =\left[\begin{array}{c}x(t)\\y(t)\end{array}\right]\ .\]</span> The differential equation, in terms of <span class="math inline">\(\vec{w(t)}\)</span> is
<span class="math display">\[\partial_t \vec{w(t)} = \left[\begin{array}{cc}a&amp;b\\c&amp;d\end{array}\right] \vec{w(t)}\ .\]</span>
Now imagine that we pick two non-colinear vectors, <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2}\)</span> that span the state space. Since the vectors are assumed to span the state, any initial condition can be written as a linear combination of those two vectors:
<span class="math display">\[\vec{w(0)} =\left[\begin{array}{c}x(0)\\y(0)\end{array}\right] = m_1 \vec{u_1} + m_2 \vec{u_2}\ .\]</span></p>
<p>For the moment, we won’t worry about how best to choose <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2}\)</span>; any two vectors that are not colinear will do.</p>
<div class="example">
<p><span id="exm:unlabeled-div-10" class="example"><strong>Example 53.2  </strong></span><span class="math inline">\(\ \)</span></p>
<p>As a running example, we’ll work with the pair of first-order differential equations
<span class="math display">\[\partial_t x = x + y\\
\partial_t y = 2 x \ \ \ \ \]</span>
which, in vector/matrix form are
<span class="math display">\[\partial_t \vec{w(t)} = \left[\begin{array}{cc}1&amp;1\\2&amp;0\end{array}\right] \vec{w(t)}\ .\]</span>
Imagine that we choose, arbitrarily, <span class="math display">\[\vec{u_1} = \color{magenta}{\left[\begin{array}{r}1\\-3\end{array}\right]}\ \ \ \text{and}\ \ \ \vec{u_2} = \color{blue}{\left[\begin{array}{r}1.0\\0\end{array}\right]}\ .\]</span></p>
<p>For the example, we’ll calculate a trajectory starting at the initial condition <span class="math inline">\(\vec{w(0)} = \left[\begin{array}{r}-1.1\\ 2.1\end{array}\right]\)</span>:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="eigenvalues.html#cb29-1" aria-hidden="true" tabindex="-1"></a>traj <span class="ot">&lt;-</span> <span class="fu">integrateODE</span>(dx <span class="sc">~</span> x <span class="sc">+</span> y, dy <span class="sc">~</span> <span class="dv">2</span><span class="sc">*</span>x, <span class="at">x=</span><span class="sc">-</span><span class="fl">1.1</span>, <span class="at">y=</span><span class="fl">2.1</span>, <span class="at">tdur=</span><span class="dv">2</span>)</span>
<span id="cb29-2"><a href="eigenvalues.html#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">traj_plot</span>(<span class="fu">y</span>(t) <span class="sc">~</span> <span class="fu">x</span>(t), traj)</span></code></pre></div>
<p><img src="MOSAIC-Calculus_files/figure-html/unnamed-chunk-25-1.png" width="90%" style="display: block; margin: auto;" /></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:vec-example-1"></span>
<img src="MOSAIC-Calculus_files/figure-html/vec-example-1-1.png" alt="The trajectory calculated starting at (-1.1, 2.1). The graph is annotated with the vectors $\vec{u_1}$ and $\vec{u_2}$ and the flow field." width="90%" />
<p class="caption">
Figure 53.1: The trajectory calculated starting at (-1.1, 2.1). The graph is annotated with the vectors <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2}\)</span> and the flow field.
</p>
</div>
<p>The initial condition (marked “0” in Figure <a href="eigenvalues.html#fig:vec-example-1">53.1</a>) is, like any other point in the state space, a linear combination of <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2}\)</span>. We can find the scalar coefficients of the linear combination using any of the methods presented in Block 5, for instance the telescope method.
We’ll illustrate with <code>qr.solve()</code>:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="eigenvalues.html#cb30-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">rbind</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">3</span>), <span class="fu">rbind</span>(<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb30-2"><a href="eigenvalues.html#cb30-2" aria-hidden="true" tabindex="-1"></a>w0 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="sc">-</span><span class="fl">1.1</span>, <span class="fl">2.1</span>)</span>
<span id="cb30-3"><a href="eigenvalues.html#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qr.solve</span>(M, w0)</span></code></pre></div>
<pre><code>##      [,1]
## [1,] -0.7
## [2,] -0.4</code></pre>
<p>So, <span class="math inline">\(\vec{w(0)} = -0.7 \vec{u_1} - 0.4 \vec{u_2}\)</span>. Keep these scalar coefficients, <span class="math inline">\(-0.7\)</span> and <span class="math inline">\(-0.4\)</span> in mind for the next example.</p>
</div>
<p>We can use <code>integrateODE()</code> to find the solution starting at any initial condition. In particular, we can find the solution <span class="math inline">\(\vec{u_1}\)</span> as the initial condition and, similarly, using <span class="math inline">\(\vec{u_2}\)</span> as the initial condition.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="eigenvalues.html#cb32-1" aria-hidden="true" tabindex="-1"></a>traj_u1 <span class="ot">&lt;-</span> <span class="fu">integrateODE</span>(dx <span class="sc">~</span> x <span class="sc">+</span> y, dy <span class="sc">~</span> <span class="dv">2</span><span class="sc">*</span>x, <span class="at">x=</span><span class="dv">1</span>, <span class="at">y=</span><span class="sc">-</span><span class="dv">3</span>, <span class="at">tdur=</span><span class="dv">2</span>)</span>
<span id="cb32-2"><a href="eigenvalues.html#cb32-2" aria-hidden="true" tabindex="-1"></a>traj_u2 <span class="ot">&lt;-</span> <span class="fu">integrateODE</span>(dx <span class="sc">~</span> x <span class="sc">+</span> y, dy <span class="sc">~</span> <span class="dv">2</span><span class="sc">*</span>x, <span class="at">x=</span><span class="dv">1</span>, <span class="at">y=</span> <span class="dv">0</span>, <span class="at">tdur=</span><span class="dv">2</span>)</span></code></pre></div>
<p>Figure <a href="eigenvalues.html#fig:vec-example-2">53.2</a> shows these trajectories.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:vec-example-2"></span>
<img src="MOSAIC-Calculus_files/figure-html/vec-example-2-1.png" alt="Trajectories from the initial conditions $\color{magenta}{\vec{u_1}}$ and $\color{blue}{\vec{u_2}}$." width="90%" />
<p class="caption">
Figure 53.2: Trajectories from the initial conditions <span class="math inline">\(\color{magenta}{\vec{u_1}}\)</span> and <span class="math inline">\(\color{blue}{\vec{u_2}}\)</span>.
</p>
</div>
<p>At first glance, the two trajectories <span class="math inline">\(\vec{u_1(t)}\)</span> and <span class="math inline">\(\vec{u_2(t)}\)</span> in Figure <a href="#fig:vec-example2"><strong>??</strong></a> that start from <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2}\)</span> might not look much like the trajectory in Figure <a href="eigenvalues.html#fig:vec-example-1">53.1</a> that starts from <span class="math inline">\(\vec{w(0)} = -0.7 \vec{u_1} - 0.4 \vec{u_2}\)</span>. But in fact there is a very simple relationship between the trajectories:
<span class="math display">\[\vec{w(t)} = -0.7 \vec{u_1(t)} - 0.4 \vec{u_2(t)}\ .\]</span>
To state the situation more generally, any solution to the differential equations can be written as a linear combination of the solutions starting at <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2}\)</span>, regardless of how <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2}\)</span> were chosen.</p>
<p>We can see this algebraically. Since <span class="math inline">\(\vec{u_1(t)}\)</span> and <span class="math inline">\(\vec{u_2(t)}\)</span> are solutions to the linear differential equation, it must be that
<span class="math display">\[\partial_t \vec{u_1(t)} = \left[\begin{array}{cc}1&amp;1\\2&amp;0\end{array}\right] \vec{u_1(t)}\ \ \text{and}\ \ \partial_t \vec{u_2(t)} = \left[\begin{array}{cc}1&amp;1\\2&amp;0\end{array}\right] \vec{u_2(t)}\ .\]</span>
Taking a linear combination of these equations gives<br />
<span class="math display">\[\partial_t \left[m_1\, \vec{u_1(t)} + m_2 \vec{u_2(t)}\right] = \left[\begin{array}{cc}1&amp;1\\2&amp;0\end{array}\right] \left[m_1\, \vec{u_1(t)} + m_2 \vec{u_2(t)}\right]\]</span>
The same will be true in general, that is, for the matrix <span class="math inline">\(\left[\begin{array}{cc}a&amp;b\\c&amp;d\end{array}\right]\)</span>.</p>
</div>
<div id="eigenvectors-and-eigenvalues" class="section level2" number="7.2">
<h2><span class="header-section-number">53.2</span> Eigenvectors and eigenvalues</h2>
<p>In the previous section, we saw that the solution to any linear differential equation starting at any initial condition can be written as a linear combination <span class="math inline">\(m_1 \vec{u_1(t)} + m_2 \vec{u_2(t)}\)</span>, where <span class="math inline">\(\vec{u_1(t)}\)</span> is the solution starting at an initial condition <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2(t)}\)</span> is the solution starting at <span class="math inline">\(\vec{u_2}\)</span>. It does not matter how <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2}\)</span> are chosen, so long as they are not colinear, that is, so long as they span the state space.</p>
<p>In this section, we’ll demonstrate that there is a particular way of selecting <span class="math inline">\(\vec{u_1}\)</span> and <span class="math inline">\(\vec{u_2}\)</span> that makes the solutions <span class="math inline">\(\vec{u_1(t)}\)</span> and <span class="math inline">\(\vec{u_2(t)}\)</span> have a very simple, purely exponential format. The vectors to be chosen are the <strong><em>eigenvectors</em></strong> of the matrix <span class="math inline">\(\left[\begin{array}{cc}a&amp;b\\c&amp;d\end{array}\right]\)</span>. We’ll call these eigenvectors <span class="math inline">\(\vec{\Lambda_1}\)</span> and <span class="math inline">\(\vec{\Lambda_2}\)</span>. (This use of the Greek letter <span class="math inline">\(\Lambda\)</span> (capital “lambda”) and it’s lower-case version <span class="math inline">\(\lambda\)</span>, is conventional in mathematics, physics, and engineering. So it’s worth learning to identify the letters.)</p>
<p>Our task in this section is to show how to compute the eigenvectors <span class="math inline">\(\vec{\Lambda_1}\)</span> and <span class="math inline">\(\vec{\Lambda_2}\)</span> and that the solutions <span class="math inline">\(\vec{\Lambda_1(t)}\)</span> and <span class="math inline">\(\vec{\Lambda_2(t)}\)</span> are in fact simple exponentials. In Chapter <a href="second-order-de.html#second-order-de">54</a> we’ll derive the formula for the eigenvectors. Here, we’ll use the R function <code>eigen()</code> to do the calculations for us.</p>
<div class="example">
<p><span id="exm:unlabeled-div-11" class="example"><strong>Example 53.3  </strong></span><span class="math inline">\(\ \)</span>
Eigenvectors can be calculated using the R function <code>eigen()</code> applied to the abcd matrix that defines the linear differential equation.</p>
<p>For the system of first-order differential equations <span class="math display">\[\partial_t x = x + y\\\partial_t y = 2x\ \ \ \ \ \]</span>
the matrix is, as we’ve seen, <span class="math display">\[\left[\begin{array}{cc}1&amp;1\\2&amp;0\end{array}\right]\ .\]</span></p>
<p>Carrying out the eigenvector calculation is straightforward:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="eigenvalues.html#cb33-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">rbind</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="fu">rbind</span>(<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb33-2"><a href="eigenvalues.html#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(M)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1]  2 -1
## 
## $vectors
##           [,1]       [,2]
## [1,] 0.7071068 -0.4472136
## [2,] 0.7071068  0.8944272</code></pre>
<p>The eigenvectors are the two columns of the matrix labeled <code>vectors</code> returned by the calculation. Here, that’s
<span class="math display">\[\vec{\Lambda_1} = \left[\begin{array}{r}0.7071\\0.7071\end{array}\right]
\ \ \ \text{and}\ \ \ \ 
\vec{\Lambda_2} = \left[\begin{array}{r}-0.4472\\0.8944\end{array}\right]\ .\]</span></p>
<p>The calculation also produces <strong><em>eigenvalues</em></strong>. Here that’s <span class="math inline">\(\lambda_1 = 2\)</span> and <span class="math inline">\(\lambda_2 = -1\)</span>.</p>
</div>
<p>We can see what’s special about <span class="math inline">\(\vec{\Lambda_1}\)</span> and <span class="math inline">\(\vec{\Lambda_2}\)</span> by plotting them along with the flow field, as in
Figure <a href="eigenvalues.html#fig:eigen-flow">53.3</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:eigen-flow"></span>
<img src="MOSAIC-Calculus_files/figure-html/eigen-flow-1.png" alt="The eigenvectors for the $\left[\begin{array}{cc}1&amp;1\\2&amp;0\end{array}\right]$ plotted along with the flow." width="90%" />
<p class="caption">
Figure 53.3: The eigenvectors for the <span class="math inline">\(\left[\begin{array}{cc}1&amp;1\\2&amp;0\end{array}\right]\)</span> plotted along with the flow.
</p>
</div>
<p>The eigenvectors mark the directions where the flow is either directly toward the fixed point or directly away from it. Here, the flow on the subspace of <span class="math inline">\(\color{magenta}{\vec{\Lambda_1}}\)</span> is away from the fixed point, while the flow along the subspace of <span class="math inline">\(\color{blue}{\vec{\Lambda_2}}\)</span> is inward to the fixed point.</p>
<p>The consequence of this alignment of the flow with the eigenvectors is that the trajectory from any initial condition <span class="math inline">\(m_1 \vec{\Lambda_1}\)</span> will have the form <span class="math inline">\(m_1(t) \vec{\Lambda_1}\)</span> and similarly for an initial condition <span class="math inline">\(m_2(t) \vec{\Lambda_2}\)</span>.</p>
<p>As we did in the previous section, let’s calculate the trajectories <span class="math inline">\(\color{magenta}{\vec{\Lambda_1(t)}}\)</span> and <span class="math inline">\(\color{blue}{\vec{\Lambda_2(t)}}\)</span> starting at the two eigenvectors and plot out the <span class="math inline">\(y(t)\)</span> component of the solution. Since we’re anticipating an exponential form for the function, we’ll use semi-log axes, where an exponential will look like a straight line.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="eigenvalues.html#cb35-1" aria-hidden="true" tabindex="-1"></a>traj_eigen1 <span class="ot">&lt;-</span> <span class="fu">integrateODE</span>(dx <span class="sc">~</span> x <span class="sc">+</span> y, dy <span class="sc">~</span> <span class="dv">2</span><span class="sc">*</span>x, <span class="at">x=</span><span class="fl">0.7071</span>, <span class="at">y=</span><span class="fl">0.7071</span>)</span>
<span id="cb35-2"><a href="eigenvalues.html#cb35-2" aria-hidden="true" tabindex="-1"></a>traj_eigen2 <span class="ot">&lt;-</span> <span class="fu">integrateODE</span>(dx <span class="sc">~</span> x <span class="sc">+</span> y, dy <span class="sc">~</span> <span class="dv">2</span><span class="sc">*</span>x, <span class="at">x=</span><span class="sc">-</span><span class="fl">0.4472</span>, <span class="at">y=</span><span class="fl">0.8944</span>)</span>
<span id="cb35-3"><a href="eigenvalues.html#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">traj_plot</span>(<span class="fu">y</span>(t) <span class="sc">~</span> t, traj_eigen1, <span class="at">color=</span><span class="st">&quot;magenta&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="eigenvalues.html#cb35-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">traj_plot</span>(<span class="fu">y</span>(t) <span class="sc">~</span> t, traj_eigen2, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-5"><a href="eigenvalues.html#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_refine</span>(<span class="fu">scale_y_log10</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="fl">0.3290</span>, <span class="fl">0.7071</span>, <span class="fl">0.8944</span>, <span class="fl">5.2248</span>)))</span></code></pre></div>
<p><img src="MOSAIC-Calculus_files/figure-html/eigen-time-series-1.png" width="90%" style="display: block; margin: auto;" />
We’ve marked the <span class="math inline">\(y\)</span> axis with the starting and ending values of each function, so that you can find the exponential parameter <span class="math inline">\(k\)</span> for each function.</p>
<p><span class="math display">\[\color{magenta}{y_1(t) = 0.7071 e^{k_1 t}}\\
\color{blue}{y_2(t)} = 0.8944 e^{k_2 t}\]</span>
To find <span class="math inline">\(k_1\)</span> and <span class="math inline">\(k_2\)</span>, plug in <span class="math inline">\(t=1\)</span> to the solution:</p>
<p><span class="math display">\[\color{magenta}{y_1(1) = 5.2248 = 0.7071 e^{k_1}} \implies k_1=2\\
\color{blue}{y_2(1) = 0.3290 = 0.8944 e^{k_2}} \implies k_2 = -1\]</span></p>
<p>Look back at the results from the <code>eigen(M)</code> calculation. These values for <span class="math inline">\(k_1\)</span> and <span class="math inline">\(k_2\)</span> are exactly the <strong><em>eigenvalues</em></strong> that were computed from the matrix <code>M</code>. In standard notation, rather than <span class="math inline">\(k_1\)</span> and <span class="math inline">\(k_2\)</span>, the notation <span class="math inline">\(\lambda_1 = k_1\)</span> and <span class="math inline">\(\lambda_2 = k_2\)</span> is preferred. (Remember, <span class="math inline">\(\lambda\)</span> is the Greek letter “lambda” in it’s lower-case form.)
Every solution to the differential equation has the form
<span class="math display">\[m_1\, e^{\lambda_1 t} \vec{\Lambda_1} + m_2\, e^{\lambda_2 t} \vec{\Lambda_2}\ .\]</span>
The scalar coefficients <span class="math inline">\(m_1\)</span> and <span class="math inline">\(m_2\)</span> can be found from the initial condition. The stability of the system depends only on <span class="math inline">\(\lambda_1\)</span> and <span class="math inline">\(\lambda_2\)</span>. If either one of these is positive, then the system is unstable.</p>
</div>
<div id="exercises-5" class="section level2" number="7.3">
<h2><span class="header-section-number">53.3</span> Exercises</h2>
<details>
<summary>
<strong>Exercise XX.XX</strong>: <span><a name="File: Exercises/child-buy-drawer.Rmd" href="#OwCtGH"><img src="www/icons8-signpost.png" title="Location: Exercises/child-buy-drawer.Rmd" width="12px"/></a><span style="color: red; font-size: 9pt;">OwCtGH</red></span>
</summary>
<p>The exercise is based on the interactive applet shown below. Click on the image to open up the applet in another tab of your browser. Then arrange so that the applet’s tab is side by side with this one. That way you can see the questions and figure out the answer at the same time.</p>
<p><a href="https://maa-statprep.shinyapps.io/142Z-Eigenflows/" target="_blank"><img src='www/eigenflow-app.png' width="50%"></a></p>
<p>We are going to look at trajectories that go round and round: oscillating solutions to the linear dynamics around a fixed point.</p>
<p>In the applet, click on the left-hand graph to set the <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> values in the [ab10] matrix. Clicking on the right-hand graph will start a trajectory (shown in red) from the place where you click.</p>
<p>You can create an oscillatory flow by clicking anywhere in the blue parabolic region in the left-hand graph. Play around with clicking in different spots in the parabolic region. Set the number of time steps for the red trajectory until you can see at least two full revolutions around the origin.</p>
<p><strong>Question A</strong> Click near (but not on) the fixed point. Which of these best describes the shape of the trajectory?</p>
<ol style="list-style-type: lower-roman">
<li><span class="Zchoice">A tightly wound spiral<span class="mcanswer">Excellent! </span></span><br />
</li>
<li><span class="Zchoice">A loosely wound spiral<span class="mcanswer">︎✘ </span></span><br />
</li>
<li><span class="Zchoice">A rectangular shape<span class="mcanswer">︎✘ </span></span><br />
</li>
<li><span class="Zchoice">Alternating between heading toward the fixed point and heading away from it.<span class="mcanswer">︎✘ </span></span></li>
</ol>
<p><strong>Question B</strong> Leaving the a and b values the same as when you answered the previous question, start the trajectory about half-way from the fixed point. How does the new trajectory compare to the one from the previous problem?</p>
<ol style="list-style-type: lower-roman">
<li><span class="Zchoice">A more tightly wound spiral<span class="mcanswer">︎✘ </span></span><br />
</li>
<li><span class="Zchoice">A more loosely wound spiral<span class="mcanswer">Correct. </span></span><br />
</li>
<li><span class="Zchoice">A spiral that goes the other way round<span class="mcanswer">︎✘ </span></span><br />
</li>
<li><span class="Zchoice">A rectangular shape<span class="mcanswer">︎✘ </span></span></li>
</ol>
<p>AN EARLY PROBLEM to explore what happens to the eigenvalues at different (a,b) values. Saddle, unstable, stable oscillation, unstable oscillation. explain what the “real part” is and what the “imaginary part” is.</p>
<p>Question: set (a,b) to close to (???, ???). Which of these is closest to the real part of the eigenvalues? Which is closest to the imaginary part of the eigenvalues.</p>
<p>Point out that there are really only two decimal numbers that appear in an eigenvalue, regardless of whether they are real or complex.</p>
<p>Can you find an (a,b) that makes the real part of the eigenvalue very small (e.g, &lt; 0.05). What accomplishes this? Compare to the eigenvalue formula.</p>
<p>Which of these conditions is sufficient that the trajectory will head away from the fixed point (eventually).</p>
<p>At least one eigenvector has a positive real part.</p>
ANOTHER PROBLEM INVOLVING C and D Click near the edge of the parabolic zone with [just say what a and b should be approximately], increase D. At what point does the spiral behavior disappear? What happens to the eigenvalues at this point.
</details>
<details>
<summary>
<strong>Exercise XX.XX</strong>: <span><a name="File: Exercises/beech-ride-bowl.Rmd" href="#Rdc7vE"><img src="www/icons8-signpost.png" title="Location: Exercises/beech-ride-bowl.Rmd" width="12px"/></a><span style="color: red; font-size: 9pt;">Rdc7vE</red></span>
</summary>
<p><strong>Question tmp-1</strong>: What are the numerical values of the eigenvalues of the matrix <span class="math inline">\(\left[\begin{array}{rc}-1 &amp; \frac{3}{4} \\ 1 &amp; 0\end{array}\right]\)</span>?</p>
<ol>
<li><p><span class="math inline">\(\frac{1}{2}\)</span> and <span class="math inline">\(-\frac{3}{2}\)</span> (+) []</p></li>
<li><p><span class="math inline">\(\frac{1}{2}\)</span> and <span class="math inline">\(-\frac{5}{2}\)</span> []</p></li>
<li><p><span class="math inline">\(\frac{1}{2}\)</span> and <span class="math inline">\(+\frac{5}{2}\)</span> []</p></li>
<li><p><span class="math inline">\(-\frac{1}{2}\)</span> and <span class="math inline">\(-\frac{5}{2}\)</span> []</p></li>
</ol>
<p><strong>Question tmp-2</strong>: What are the numerical values of the eigenvalues of the matrix <span class="math inline">\(\left[\begin{array}{rc}0 &amp; \frac{1}{2} \\ 1 &amp; 0\end{array}\right]\)</span>?</p>
<ol>
<li><p><span class="math inline">\(\pm\sqrt{2}/2\)</span> (+) []</p></li>
<li><p><span class="math inline">\(\pm\sqrt{2}\)</span> []</p></li>
<li><p><span class="math inline">\(\pm 2\)</span> []</p></li>
<li><p><span class="math inline">\(\pm\frac{1}{2}\)</span> []</p></li>
</ol>
<p>Eigenvalues are important because they dramatically simplify the interpretation of matrices and of dynamical system behavior near fixed points.</p>
<p>Eigenvalues are numbers. To use the language of linear combinations, an eigenvalue is a <em>scalar</em>. As you know, when you multiply a vector times a scalar, the result has the same direction (or the exact opposite direction) but might be longer or shorter. Like this:
<span class="math display">\[ 3 \left[\begin{array}{c}1\\2 \end{array}\right] = \left[\begin{array}{c}3\\6 \end{array}\right]\ \ \ \ \text{or}\ \ \ \ \ 
-4 \left[\begin{array}{r}3\\-1 \end{array}\right] = \left[\begin{array}{r}-12\\4\end{array}\right]\]</span>
In contrast, <strong>matrix</strong> multiplication of a vector can generate a result that has a <em>different direction</em> than the original vector, like this:</p>
<p><span class="math display">\[\left[\begin{array}{rc}0 &amp; \frac{1}{2} \\ 1 &amp; 0\end{array}\right]\cdot \left[\begin{array}{c}2 \\ 1\end{array}\right] =
\left[\begin{array}{c}\frac{1}{2} \\2\end{array}\right]\ \ \ \ \text{or}\ \ \ \ \left[\begin{array}{rc}-1 &amp; \frac{3}{4} \\ 1 &amp; 0\end{array}\right]\cdot \left[\begin{array}{r}1 \\ -4\end{array}\right] =
\left[\begin{array}{c}4 \\1\end{array}\right]\]</span></p>
<p>An <strong>eigenvector</strong> is a vector has a seemingly magical property with respect to multiplication by the matrix it characterizes: the result of the multiplication is a vector that has the same direction as the original but scaled by it’s corresponding eigenvalue <span class="math inline">\(\lambda\)</span>. That is, if <span class="math inline">\(\lambda\)</span> is an eigenvalue of <span class="math inline">\({\mathbf M}\)</span> and <span class="math inline">\({\mathbf \Lambda}\)</span> is the corresponding eigenvector:
<span class="math display">\[{\mathbf M}\cdot {\mathbf \Lambda} = \lambda {\mathbf \Lambda}\]</span></p>
<p><strong>Question tmp-3</strong>: Which of these is an eigenvector of the matrix <span class="math inline">\(\left[\begin{array}{rc}-1 &amp; \frac{3}{4} \\ 1 &amp; 0\end{array}\right]\)</span>? (Hint: Multiply the matrix by each of the vectors listed. For one of them, the result of the multiplication will be aligned with the vector used. You can use the constant of proportionality to answer the next question, but you’ll have to start by choosing the right one of the options that follow.)</p>
<ol>
<li><p><span class="math inline">\(\left[\begin{array}{r}-3\\2\end{array}\right]\)</span> (+) []</p></li>
<li><p><span class="math inline">\(\left[\begin{array}{r}3\\2\end{array}\right]\)</span> []</p></li>
<li><p><span class="math inline">\(\left[\begin{array}{r}-2\\3\end{array}\right]\)</span> []</p></li>
<li><p><span class="math inline">\(\left[\begin{array}{r}2\\3\end{array}\right]\)</span> []</p></li>
</ol>
<p><strong>Question tmp-4</strong>: What is the eigenvalue associated with the correct answer from the previous problem?</p>
<ol>
<li><p>-1.5 (+) []</p></li>
<li><p>-1 []</p></li>
<li><p>-0.5 []</p></li>
<li><p>0.5 []</p></li>
<li><p>1.5 []</p></li>
</ol>
<p><strong>Question tmp-5</strong>: Consider the two matrices <span class="math display">\[{\mathbf M}_1 = \left[\begin{array}{rr}5 &amp; 6 \\0 &amp; 1\end{array}\right]\ \ \text{and}\ \ \left[\begin{array}{rr}-3 &amp; 1 \\0 &amp; 1\end{array}\right]\]</span> Which of the following is <strong>not</strong> an eigenvector of <span class="math inline">\({\mathbf M}_1\)</span> or of <span class="math inline">\({\mathbf M}_2\)</span>? (We’ve rounded off to two decimal places and provided a sandbox for calculations.)</p>
<ol>
<li><p><span class="math inline">\(\left[\begin{array}{r}6\\1\end{array}\right]\)</span> []</p></li>
<li><p><span class="math inline">\(\left[\begin{array}{r}-1\\1\end{array}\right]\)</span> []</p></li>
<li><p><span class="math inline">\(\left[\begin{array}{r}3\\2\end{array}\right]\)</span> (+) []</p></li>
<li><p><span class="math inline">\(\left[\begin{array}{r}3.02\\10\end{array}\right]\)</span> []</p></li>
<li><p><span class="math inline">\(\left[\begin{array}{r}3.30\\-1\end{array}\right]\)</span> []</p></li>
</ol>
<p>You can use the sandbox below either for arithmetic calculations that you hand write or to use matrix-related R commands. In the initial code in the sandbox is a test that shows whether a vector <code>v</code> is an eigenvector of <code>M</code>. In this example it is and has eigenvalue 0.5615 (rounding off to 4 decimal places). You can print out <code>M</code> or <code>v</code> in the ordinary way, with the simple commands <code>M</code> or <code>v</code> respectively.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="eigenvalues.html#cb36-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">cbind</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">2</span>), <span class="fu">cbind</span>(<span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb36-2"><a href="eigenvalues.html#cb36-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fl">5.6155</span>, <span class="dv">10</span>)</span>
<span id="cb36-3"><a href="eigenvalues.html#cb36-3" aria-hidden="true" tabindex="-1"></a>(M <span class="sc">%*%</span> v) <span class="sc">/</span> v <span class="co"># element-by-element division</span></span></code></pre></div>
</details>
<details>
<summary>
<strong>Exercise XX.XX</strong>: <span><a name="File: Exercises/panda-teach-door.Rmd" href="#PD3CiZ"><img src="www/icons8-signpost.png" title="Location: Exercises/panda-teach-door.Rmd" width="12px"/></a><span style="color: red; font-size: 9pt;">PD3CiZ</red></span>
</summary>
<p>In this exercise, you’ll be using an app that allows you to set <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> in the [ab10] matrix and hunt for eigenvectors.</p>
<p><a href="https://maa-statprep.shinyapps.io/142Z-Eigenflows/" target="_blank">
<img src="www/eigenflow-app.png" width="60%">
</a></p>
<p>Open up the app in another browser tab and arrange it side-by-side with this document, so you can see both at the same time.</p>
<p>You used a somewhat similar app when exploring linear, two-dimensional finite-difference equations. <a href="https://maa-statprep.shinyapps.io/142Z-Matrix-iteration/">Here’s a link</a>, but you don’t need to open that app for this exercise.</p>
<p>This new app does a few things differently:</p>
<ul>
<li>In the old app, you had four number-entry boxes to set the values of the [abcd] matrix. Here, because we’re using the [ab10] format, you need only set <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. You can do this by clicking within the left-hand graph.</li>
<li>The a-b selector graph is annotated with the type of generic behavior that the differential-equation system will show for any combination of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. This allows you to reason backward from the behavior you are interested in to the corresponding values of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. Since the type of behavior is encoded in the eigenvalues, you are effectively inverting the eigenvalue formula to find <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>.</li>
<li>The flow field (right-hand graph) shows <em>stream-lines</em> of continuous-time motion. Imagine you had a bunch of glitter which you cast out over a pool of water with a given flow pattern. If you took a time-exposure photo, you would see each piece of glitter as it moved along with the water in which it is embedded.</li>
<li>You can click in the flow field to start a trajectory at that point. You can control the time domain—that is, how long is the time exposure of the photo—with the radio buttons at the bottom.</li>
<li>There is a thin, green line annotating the flow field. This line runs from the fixed point (right in the center) in the direction of the point on which you click to start a trajectory. A vector with the same orientation as the green line is given numerically below the graph. This orientation is also described using an angle measurement in degrees.</li>
<li>There is no display of the <em>solution</em>, that is, <span class="math inline">\(x()\)</span> versus <span class="math inline">\(t\)</span>. This is because we want you to understand the <em>geometry</em> of the flow.</li>
</ul>
<p>First, play around with the app. Choose miscellaneous values of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, observe the flow, and click in the flow field to draw a red trajectory. Notice what happens when you make the number of steps larger or smaller. In unstable directions, you can get a good view of the trajectory by starting it near the fixed point. If you start it at the periphery of the graph, most of the trajectory will be outside the display. And if the number of steps is very small, you may not see it at all because the glyph is so thin near the start.</p>
<p>When coming from a stable direction, click near the periphery of the graph to get a good view, since the red trajectory will naturally be heading in towards the origin. When estimating the orientation of an eigenvector, try to get the green line heading straight down the middle of the red trajectory. This often requires a bit of fiddling, moving the starting point just a tiny amount to find one that is just right.</p>
<p>When you are <em>on</em> an eigenvector, the trajectory will be dead straight on the green line. Any trajectory not starting on an eigenvector will be curved to a greater or lesser extent, depending on the relative sizes of the eigenvalues.</p>
<p>In the following questions, pick the choice <strong>closest</strong> to the answer you found. The exact choice of <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> stemming from a click depends somewhat on the graphics resolution of your display, so you should expect only to be able to get close to the <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> values given in the question.</p>
<p><strong>Question tmp-6</strong>: Set <span class="math inline">\(a=-1.0\)</span> and <span class="math inline">\(b = 0.5\)</span> (or as close as you can get) and observe the flow. This is a saddle: stable in one direction, unstable in another. There will be one stable eigenvector, where the flow moves <strong>directly outward</strong> from the origin, and one unstable eigenvector, where the flow moves <strong>directly inward</strong> toward the origin. Which one of these is the orientation (in degrees) of the unstable eigenvector?</p>
<ol>
<li><p>-149.7 []</p></li>
<li><p>-63.6 []</p></li>
<li><p>-31.7 []</p></li>
<li><p>69.1 (+) []</p></li>
<li><p>73.5 []</p></li>
<li><p>106.6 []</p></li>
<li><p>143.7 []</p></li>
<li><p>149 []</p></li>
</ol>
<p><strong>Question tmp-7</strong>: Which of these best describes the eigenvalue corresponding to the unstable eigenvector?</p>
<ol>
<li><p>Negative and real []</p></li>
<li><p>Zero and real []</p></li>
<li><p>Positive and real (+) []</p></li>
<li><p>Complex with a negative real part []</p></li>
<li><p>Complex with a positive real part []</p></li>
</ol>
<p><strong>Question tmp-8</strong>: Keeping <span class="math inline">\(a=-1.0\)</span> and <span class="math inline">\(b = 0.5\)</span>, hunt for the stable eigenvector. Which one of these is the orientation (in degrees) of the stable eigenvector?</p>
<ol>
<li><p>-149.7 []</p></li>
<li><p>-63.6 []</p></li>
<li><p>-31.7 []</p></li>
<li><p>69.1 []</p></li>
<li><p>73.5 []</p></li>
<li><p>106.6 []</p></li>
<li><p>143.7 (+) []</p></li>
<li><p>149 []</p></li>
</ol>
<hr />
<p><strong>Question tmp-9</strong>: Set <span class="math inline">\(a=2\)</span> and <span class="math inline">\(b = -0.5\)</span> and observe the flow. This is a source: all initial conditions lead to motion away from the fixed point. But for this <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>, some directions are “faster” than others. Which one of these is the orientation (in degrees) of the fast eigenvector?</p>
<ol>
<li><p>-149.7 (+) []</p></li>
<li><p>-63.6 []</p></li>
<li><p>-31.7 []</p></li>
<li><p>69.1 []</p></li>
<li><p>73.5 []</p></li>
<li><p>106.6 []</p></li>
<li><p>143.7 []</p></li>
<li><p>149 []</p></li>
</ol>
<p><strong>Question tmp-10</strong>: Keeping <span class="math inline">\(a=2\)</span> and <span class="math inline">\(b = -0.5\)</span>, what is the orientation of the slow eigenvector?</p>
<ol>
<li><p>-149.7 []</p></li>
<li><p>-63.6 []</p></li>
<li><p>-31.7 []</p></li>
<li><p>69.1 []</p></li>
<li><p>73.5 (+) []</p></li>
<li><p>106.6 []</p></li>
<li><p>143.7 []</p></li>
<li><p>149 []</p></li>
</ol>
<p><strong>Question tmp-11</strong>: Staying with the flow from <span class="math inline">\(a=2\)</span> and <span class="math inline">\(b = -0.5\)</span>, which of these best describes the pair of eigenvalues?</p>
<ol>
<li><p>Both are real and positive (+) []</p></li>
<li><p>Both are real and negative []</p></li>
<li><p>One is complex, the other real []</p></li>
<li><p>Both are complex, one has negative real part []</p></li>
</ol>
<hr />
<p><strong>Question tmp-12</strong>: Set <span class="math inline">\(a=-2\)</span> and <span class="math inline">\(b = -0.5\)</span> and observe the flow. This is a sink: all initial conditions lead to motion toward the fixed point. Which one of these is the orientation (in degrees) of the fast eigenvector?</p>
<ol>
<li><p>-149.7 []</p></li>
<li><p>-63.6 []</p></li>
<li><p>-31.7 []</p></li>
<li><p>69.1 []</p></li>
<li><p>73.5 []</p></li>
<li><p>106.6 []</p></li>
<li><p>143.7 []</p></li>
<li><p>149 (+) []</p></li>
</ol>
<p><strong>Question tmp-13</strong>: Keeping <span class="math inline">\(a=-2\)</span> and <span class="math inline">\(b = -0.5\)</span>, what is the orientation of the slow eigenvector?</p>
<ol>
<li><p>-149.7 []</p></li>
<li><p>-63.6 []</p></li>
<li><p>-31.7 []</p></li>
<li><p>69.1 []</p></li>
<li><p>73.5 []</p></li>
<li><p>106.6 (+) []</p></li>
<li><p>143.7 []</p></li>
<li><p>149 []</p></li>
</ol>
<p><strong>Question tmp-14</strong>: Staying with the flow from <span class="math inline">\(a=2\)</span> and <span class="math inline">\(b = -0.5\)</span>, which of these best describes the pair of eigenvalues?</p>
<ol>
<li><p>Both are real and positive (+) []</p></li>
<li><p>Both are real and negative []</p></li>
<li><p>One is complex, the other real []</p></li>
<li><p>Both are complex, one has negative real part []</p></li>
<li><p>Both are complex, both have negative real part []</p></li>
</ol>
<hr />
<p><strong>Question tmp-15</strong>: Set <span class="math inline">\(a=-1\)</span> and <span class="math inline">\(b = -1\)</span> and observe the flow. This is a node: the flow is spiral with the fixed point at the center. Is the flow stable or unstable?</p>
<ol>
<li><p>stable (+) []</p></li>
<li><p>unstable []</p></li>
<li><p>neither stable nor unstable [Is it getting closer to the fixed point or further away? That’s the question that determines stability.]</p></li>
</ol>
<p><strong>Question tmp-16</strong>: Keeping <span class="math inline">\(a=-1\)</span> and <span class="math inline">\(b = -1\)</span>, what can you correctly say about the eigenvectors?</p>
<ol>
<li><p>They have almost the same orientation []</p></li>
<li><p>There is only one eigenvector [There are almost aways two eigenvectors.]</p></li>
<li><p>There are no eigenvectors (+) [This is true in the sense that there is no place where the motion is on a straight line toward or away from the origin.]</p></li>
</ol>
<p><strong>Question tmp-17</strong>: Staying with the flow from <span class="math inline">\(a=2\)</span> and <span class="math inline">\(b = -0.5\)</span>, which of these best describes the pair of eigenvalues?</p>
<ol>
<li><p>Both are real and positive (+) []</p></li>
<li><p>Both are real and negative []</p></li>
<li><p>One is complex, the other real []</p></li>
<li><p>Both are complex, one has negative real part []</p></li>
<li><p>Both are complex, both have negative real part []</p></li>
</ol>
<hr />
<p><strong>Question tmp-18</strong>: Set <span class="math inline">\(a=0\)</span> and some <span class="math inline">\(b &lt; 0\)</span>. The result will be a trajectory that goes around in a closed loop. (You will want to make the number of steps large to see a complete loop.) You may not be able to click on exactly <span class="math inline">\(a=0\)</span>, but you should be able to get close enough that the trajectory is a very tightly wound spiral. We’re interested here in how many cycles the trajectory covers in a fixed number of time steps, that is, whether the trajectory moves quickly or slowly around the loop. Which of these statements is true about the relationship between <span class="math inline">\(b\)</span> and the speed of the motion?</p>
<ol>
<li><p>There’s no relationship between <span class="math inline">\(b\)</span> and speed of oscillation. []</p></li>
<li><p>When <span class="math inline">\(b\)</span> is closer to zero, the speed is higher. []</p></li>
<li><p>When <span class="math inline">\(b\)</span> is further from zero, the speed is higher. (+) []</p></li>
</ol>
<p><strong>Question tmp-19</strong>: We’re going to look at the relationship between the eigenvalues and the speed of oscillation. Keep <span class="math inline">\(a=0\)</span> and <span class="math inline">\(b &lt; 0\)</span>, which guarantees that the motion will be circular. Vary <span class="math inline">\(b\)</span>, each time observing how many loops the trajectory makes (for a fixed number of steps), and what the eigenvalues are. Which of these statements is <strong>not</strong> true about the speed of oscillation and the eigenvalues.</p>
<ol>
<li><p>The larger the magnitude of the imaginary part of the eigenvalues, the faster the oscillation. []</p></li>
<li><p>The two eigenvalues have exactly the same imaginary part, except one is positive and the other negative. []</p></li>
<li><p>The speed of oscillation relates to the <em>difference</em> between the imaginary part of the eigenvalues. (+) []</p></li>
<li><p>The real part of the eigenvalues is the same for both when there is oscillatory motion. []</p></li>
</ol>
</details>
<p>EXERCISES: Give numbers for <span class="math inline">\(abcd\)</span> and <span class="math inline">\(x(0)\)</span> and <span class="math inline">\(\partial_t x(0)\)</span>. Find the eigenvalues and <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>.</p>
<p>EXERCISE: CALCULATE THE EIGENVALUES and eigenvectors from a series of matrices. What is their stability? What is the solution starting from this or that initial condition.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="equilibria.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="second-order-de.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dtkaplan/MOSAIC-Calculus/shared/B6-eigen.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/dtkaplan/MOSAIC-Calculus/shared/B6-eigen.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
