<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 52 Equilibrium and transient | MOSAIC-Calculus.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.24.1 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 52 Equilibrium and transient | MOSAIC-Calculus.knit" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 52 Equilibrium and transient | MOSAIC-Calculus.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modeling-dynamics.html"/>
<link rel="next" href="eigenvalues.html"/>
<script src="libs/header-attrs-2.13/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>
<span class="math inline">
\(\newcommand{\line}{\text{line}}
\newcommand{\hump}{\text{hump}}
\newcommand{\sigmoid}{\text{sigmoid}}
\newcommand{\recip}{\text{recip}}
\newcommand{\diff}[1]{{\cal D}_#1}
\newcommand{\pnorm}{\text{pnorm}}
\newcommand{\dnorm}{\text{dnorm}}
\let\origvec\vec
\let\origmathit\mathit
\let\orighat\hat
\let\origbar\bar
\newcommand{\vec}[1]{\overset{{\rule[-1pt]{0mm}{1mm}}\rightharpoonup}{\mathbf{#1}}}
\newcommand{\bar}[1]{\overset{{\rule[-1pt]{12pt}{.5mm}}}{\mathbf{#1}}}
\newcommand{\mathit}[1]{\underset{\leftharpoondown}{\overset{{\rightharpoonup}}{\large\mathbf #1}}}
\newcommand{\hat}[1]{\widehat{\ \mathbf#1\ }}
\newcommand{\len}[1]{{\|{\mathbf #1}\|}}
\newcommand{\tvec}[1]{\overset{\uparrow}{\mathbf #1}}
\newcommand{\tmat}[1]{\overset{\leftrightarrows}{\mathbf #1}}
\newcommand{\perpendicularto}[2]{#1\!\perp\!#2}
\newcommand{\modeledby}[2]{#1\!\sim\!#2}
\newcommand{\CC}[1]{\color{#648fff}{#1}}
\newcommand{\CE}[1]{\color{#785ef0}{#1}}
\newcommand{\CA}[1]{\color{#dc267f}{#1}}
\newcommand{\CB}[1]{\color{#fe6100}{#1}}
\newcommand{\CD}[1]{\color{#ffb000}{#1}}\)
</span>



<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="mosaic-calc-style-copy.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="../docs/welcome-to-calculus.html">Welcome to calculus</li>
<li><a href="../block-1/change.html">Block 1: Functions & quantities</a></li>
<li><a href="../block-2/change-relationships.html">Block 2: Differentiation</a></li>
<li><a href="../block-3/change-accumulation.html">Block 3: Accumulation</a></li>
<li><a href="../block-4/block4-intro.html">Block 4: Manifestations</a></li>
<li><a href="../block-5/vectors.html">Block 5: Linear combinations</a></li>
<hr>
<li><strong><a href="../block-6/diff-eq-intro.html">Block 6: Dynamics</a></strong></li>

<li class="divider"></li>
<li class="chapter" data-level="47" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html"><i class="fa fa-check"></i><b>47</b> Differential equations<span></span></a>
<ul>
<li class="chapter" data-level="47.1" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#dynamical-systems"><i class="fa fa-check"></i><b>47.1</b> Dynamical systems<span></span></a></li>
<li class="chapter" data-level="47.2" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#state"><i class="fa fa-check"></i><b>47.2</b> State<span></span></a></li>
<li class="chapter" data-level="47.3" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#state-space"><i class="fa fa-check"></i><b>47.3</b> State space<span></span></a></li>
<li class="chapter" data-level="47.4" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#dynamics"><i class="fa fa-check"></i><b>47.4</b> Dynamics<span></span></a></li>
<li class="chapter" data-level="47.5" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#state-space-and-flow-field"><i class="fa fa-check"></i><b>47.5</b> State space and flow field<span></span></a></li>
<li class="chapter" data-level="47.6" data-path="diff-eq-intro.html"><a href="diff-eq-intro.html#exercises"><i class="fa fa-check"></i><b>47.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="48" data-path="solve-DE.html"><a href="solve-DE.html"><i class="fa fa-check"></i><b>48</b> Finding a “solution”<span></span></a>
<ul>
<li class="chapter" data-level="48.1" data-path="solve-DE.html"><a href="solve-DE.html#the-flow-field"><i class="fa fa-check"></i><b>48.1</b> The flow field<span></span></a></li>
<li class="chapter" data-level="48.2" data-path="solve-DE.html"><a href="solve-DE.html#euler-method"><i class="fa fa-check"></i><b>48.2</b> Euler method<span></span></a></li>
<li class="chapter" data-level="48.3" data-path="solve-DE.html"><a href="solve-DE.html#symbolic-solutions-ODE"><i class="fa fa-check"></i><b>48.3</b> Symbolic solutions<span></span></a></li>
<li class="chapter" data-level="48.4" data-path="solve-DE.html"><a href="solve-DE.html#exercises-1"><i class="fa fa-check"></i><b>48.4</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="49" data-path="flow-on-line.html"><a href="flow-on-line.html"><i class="fa fa-check"></i><b>49</b> Flows on the line<span></span></a>
<ul>
<li class="chapter" data-level="49.1" data-path="flow-on-line.html"><a href="flow-on-line.html#dynamical-function-and-flow"><i class="fa fa-check"></i><b>49.1</b> Dynamical function and flow<span></span></a></li>
<li class="chapter" data-level="49.2" data-path="flow-on-line.html"><a href="flow-on-line.html#generic-behavior"><i class="fa fa-check"></i><b>49.2</b> Generic behavior<span></span></a></li>
<li class="chapter" data-level="49.3" data-path="flow-on-line.html"><a href="flow-on-line.html#linearization"><i class="fa fa-check"></i><b>49.3</b> Linearization<span></span></a></li>
<li class="chapter" data-level="49.4" data-path="flow-on-line.html"><a href="flow-on-line.html#bifurcation"><i class="fa fa-check"></i><b>49.4</b> Bifurcation<span></span></a></li>
<li class="chapter" data-level="49.5" data-path="flow-on-line.html"><a href="flow-on-line.html#exercises-2"><i class="fa fa-check"></i><b>49.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="50" data-path="flow-on-plane.html"><a href="flow-on-plane.html"><i class="fa fa-check"></i><b>50</b> Flows on the plane<span></span></a>
<ul>
<li class="chapter" data-level="50.1" data-path="flow-on-plane.html"><a href="flow-on-plane.html#qualitative-stability"><i class="fa fa-check"></i><b>50.1</b> Generic behaviors<span></span></a></li>
<li class="chapter" data-level="50.2" data-path="flow-on-plane.html"><a href="flow-on-plane.html#linearization-1"><i class="fa fa-check"></i><b>50.2</b> Linearization<span></span></a></li>
<li class="chapter" data-level="50.3" data-path="flow-on-plane.html"><a href="flow-on-plane.html#exercises-3"><i class="fa fa-check"></i><b>50.3</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="51" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html"><i class="fa fa-check"></i><b>51</b> Modeling dynamics<span></span></a>
<ul>
<li class="chapter" data-level="51.1" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#a-single-state-quantity"><i class="fa fa-check"></i><b>51.1</b> A single state quantity<span></span></a></li>
<li class="chapter" data-level="51.2" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#multiple-state-quantities"><i class="fa fa-check"></i><b>51.2</b> Multiple state quantities<span></span></a></li>
<li class="chapter" data-level="51.3" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#classical-phase-plane-models"><i class="fa fa-check"></i><b>51.3</b> Classical phase-plane models<span></span></a></li>
<li class="chapter" data-level="51.4" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#epidemic"><i class="fa fa-check"></i><b>51.4</b> Epidemic<span></span></a></li>
<li class="chapter" data-level="51.5" data-path="modeling-dynamics.html"><a href="modeling-dynamics.html#exercises-4"><i class="fa fa-check"></i><b>51.5</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="52" data-path="equilibria.html"><a href="equilibria.html"><i class="fa fa-check"></i><b>52</b> Equilibrium and transient<span></span></a>
<ul>
<li class="chapter" data-level="52.1" data-path="equilibria.html"><a href="equilibria.html#one-state-variable"><i class="fa fa-check"></i><b>52.1</b> One state variable<span></span></a></li>
<li class="chapter" data-level="52.2" data-path="equilibria.html"><a href="equilibria.html#two-state-variables"><i class="fa fa-check"></i><b>52.2</b> Two state variables<span></span></a></li>
</ul></li>
<li class="chapter" data-level="53" data-path="eigenvalues.html"><a href="eigenvalues.html"><i class="fa fa-check"></i><b>53</b> Eigenvalues, eigenvectors<span></span></a>
<ul>
<li class="chapter" data-level="53.1" data-path="eigenvalues.html"><a href="eigenvalues.html#vector-solutions-to-linear-differential-equations"><i class="fa fa-check"></i><b>53.1</b> Vector solutions to linear differential equations<span></span></a></li>
<li class="chapter" data-level="53.2" data-path="eigenvalues.html"><a href="eigenvalues.html#eigenvectors-and-eigenvalues"><i class="fa fa-check"></i><b>53.2</b> Eigenvectors and eigenvalues<span></span></a></li>
<li class="chapter" data-level="53.3" data-path="eigenvalues.html"><a href="eigenvalues.html#exercises-5"><i class="fa fa-check"></i><b>53.3</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="54" data-path="second-order-de.html"><a href="second-order-de.html"><i class="fa fa-check"></i><b>54</b> Force-balance equations<span></span></a>
<ul>
<li class="chapter" data-level="54.1" data-path="second-order-de.html"><a href="second-order-de.html#ballistics"><i class="fa fa-check"></i><b>54.1</b> Ballistics<span></span></a></li>
<li class="chapter" data-level="54.2" data-path="second-order-de.html"><a href="second-order-de.html#the-harmonic-oscillator"><i class="fa fa-check"></i><b>54.2</b> The harmonic oscillator<span></span></a></li>
<li class="chapter" data-level="54.3" data-path="second-order-de.html"><a href="second-order-de.html#exponential-or-sinusoid"><i class="fa fa-check"></i><b>54.3</b> Exponential or sinusoid?<span></span></a></li>
<li class="chapter" data-level="54.4" data-path="second-order-de.html"><a href="second-order-de.html#exponentials-with-imaginary-inputs"><i class="fa fa-check"></i><b>54.4</b> Exponentials with “imaginary” inputs<span></span></a></li>
<li class="chapter" data-level="54.5" data-path="second-order-de.html"><a href="second-order-de.html#damping"><i class="fa fa-check"></i><b>54.5</b> Damping<span></span></a></li>
<li class="chapter" data-level="54.6" data-path="second-order-de.html"><a href="second-order-de.html#exercises-6"><i class="fa fa-check"></i><b>54.6</b> Exercises<span></span></a></li>
</ul></li>
<li class="chapter" data-level="55" data-path="forcing.html"><a href="forcing.html"><i class="fa fa-check"></i><b>55</b> Forcing and resonance<span></span></a>
<ul>
<li class="chapter" data-level="55.1" data-path="forcing.html"><a href="forcing.html#car-following-dynamics"><i class="fa fa-check"></i><b>55.1</b> Car following dynamics<span></span></a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="equilibria" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 52</span> Equilibrium and transient<a href="equilibria.html#equilibria" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div style="float:right;">
<a href="https://github.com/ProjectMOSAIC/MOSAIC-Calculus/blob/main/Block-6/B6-equalibria.Rmd"><img src="www/icons/edit.png" /></a>
</div>
<!--
7. Fixed points of nonlinear systems in the phase plane 
    a. Objectives/topics
        i. Determine fixed points and linearize the system around the fixed points
        i. Flow field of the linear approximation
        i. Matrix representation of the flow field
        i. Iteration of matrices
-->
<p>Many of the natural and constructed objects and systems that we encounter—buildings, bridges, airplanes, the orbits of satellites, heating systems, birds in flight, and so on—are more fully understood if seen as dynamical systems. That may seem strange; a building doesn’t move (we hope!), an airplane stays in steady flight, the seasons have been steady in their progression for as long as records have been kept. And yet … a building might be shaken and even destroyed by an earthquake, airplanes require pilots and control systems for steady flight. Even satellites in far Earth orbit can drift from their desired positions and attitudes and require control corrections.</p>
<p>A system is said to be in <strong><em>steady state</em></strong> when it stays put, unchanging. Another term often used to express such constancy is <strong><em>equilibrium</em></strong> which occurs when the various forces or processes acting on the system <strong><em>balance out.</em></strong> In the language of dynamical systems, the equilibrium state of a system is called a <strong><em>fixed point</em></strong>. Mathematically, this is a coordinate in the state space where all the right-hand sides of the differential equations equal zero. For a two-dimensional system with dynamics <span class="math display">\[\partial_t x = f(x, y)\\\partial_t y = g(x,y)\ ,\]</span> a fixed point will be a particular value for the state which we’ll write as <span class="math inline">\((x^\star, y^\star)\)</span> where both <span class="math inline">\(f(x^\star, y^\star) = 0\)</span> and <span class="math inline">\(g(x^\star, y^\star) = 0\)</span>.</p>
<p>An important vocabulary word in dynamics is <strong><em>transient</em></strong>. In everyday speech, this means something like “just passing through.” It’s the same in dynamics: that part of the trajectory which precedes stable, fixed behavior such as at a fixed point. Transients occur whenever a dynamical system has an initial state not on a stable, fixed state. They are also common in systems that are disrupted by some external force, for example in the recovery of an electrical power distribution grid after a disturbance such as an ice storm. After a sharp bang, the ringing in your ears is a transient. When you stand up too suddenly, the “stars” you see are a transient due to diminished blood flow. Turn on an oven? The transient is the warming up until the oven reaches the temperature setting.</p>
<p>Although transients are … well, transient, they can be very important. Key to the Wright Brothers success was their recognition that air turbulence elicits transients in attitude and that aircraft need control systems that can work fast enough for the craft to survive the transient. If you have driven a car with a broken suspension, you’ll know that it can be hard to control after the transient caused by hitting a bump in the road.</p>
<p>Small disturbances often elicit transients that decay away exponentially. Such transients, like all exponentially decaying processes, can be characterized by a half life: the time it takes the transient to shrink to half its original value. (Not all transients decay exponentially, but that’s a story for another course.)</p>
<p>In this chapter, we’ll study the quantitative response to dynamical systems with a fixed point when the state
is perturbed by some outside force. Our focus will be on linear or linearized dynamical functions, which are generally an excellent description of dynamics near a fixed point.</p>
<div id="one-state-variable" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">52.1</span> One state variable<a href="equilibria.html#one-state-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Linear systems with one state variable have simple dynamics:
<span class="math display">\[\partial_t y = k y\]</span> which has a fixed point at <span class="math inline">\(y^\star = 0\)</span>. Even dynamics like <span class="math inline">\(\partial_t x = k x + b\)</span> can be easily transformed into this simple form; the fixed point is <span class="math inline">\(x^\star = - b/a\)</span> and defining <span class="math inline">\(y \equiv x - x^\star\)</span> gives the <span class="math inline">\(\partial_t y = k y\)</span> form.</p>
<p>The solution is also simple: <span class="math inline">\(y(t) = y_0\  e^{kt}\)</span>, where <span class="math inline">\(y_0\)</span> is the initial condition on <span class="math inline">\(y\)</span>. If the parameter <span class="math inline">\(k &lt; 0\)</span>, the dynamics are exponential decay to the fixed point. If <span class="math inline">\(0 &lt; k\)</span>, the dynamics are exponential growth away from the fixed point.</p>
</div>
<div id="two-state-variables" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">52.2</span> Two state variables<a href="equilibria.html#two-state-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If the state variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> are measured with respect to a fixed point, the differential equation of the linear or linearized system is:
<span class="math display">\[\partial_t x = a x + b y\\
\partial_t y = c x + d y\]</span></p>
<p>Exponentials are an important form of ansatz for linear differential equations. To show why, let’s review the solution to <span class="math inline">\(\partial_t x = k x\)</span>, but assume that all we know is that the solution is an exponential function of time: <span class="math inline">\(x(t) = A e^{\lambda t}\)</span> and that we don’t yet know the parameters <span class="math inline">\(A\)</span> or <span class="math inline">\(\lambda\)</span>. As usual for an ansatz, we plug it into both sides of the differential equation, giving <span class="math display">\[\partial_t A e^{\lambda t} = k A e^{\lambda t}\ \ \implies \lambda A e^{\lambda t} = k A e^{\lambda t}\ \ \implies \lambda = k\ .\]</span> Now we know the value of <span class="math inline">\(\lambda\)</span>.</p>
<p>What about <span class="math inline">\(A\)</span>? Evaluate the solution at <span class="math inline">\(t=0\)</span>. This gives <span class="math inline">\(x(0) = A e^{\lambda 0} = A\)</span>. So we know <span class="math inline">\(A\)</span> is the initial condition <span class="math inline">\(x(0)\)</span> (which we usually abbreviate <span class="math inline">\(x_0\)</span>).</p>
<p>We’ll try the same approach with the two-state variable system, but we’ll start with a special case where some of the parameters <span class="math inline">\(a, b, c\)</span>, and <span class="math inline">\(d\)</span> are zero.</p>
<p><span class="math display">\[\require{cancel}\text{Simplification:}\ \ \  \ \ \begin{array}{l}\partial_t x  = \cancel{ax}  +  b y\\\partial_t y =\ c x + \cancel{dy}\end{array}\ .\]</span>
We’re going to modify the equations a little, specifically, we’ll take the derivative with respect to time of both sides of the top equation, giving:
<span class="math display">\[\partial_{tt} x = b\,  \partial_{t\ }y\\ 
\partial_{t\ } y  =  c\, x \]</span>
Substitute in the value for <span class="math inline">\(\partial_t y\)</span> from the bottom equation to get a single, second-order differential equation:
<span class="math display">\[ \partial_{tt} x = b\, c\, x\ .\]</span></p>
<p>Plug in the usual ansatz, <span class="math inline">\(x(t) = A e^{\lambda t}\)</span> to get
<span class="math display">\[\lambda^2 A e^{\lambda t} = b\,c\, A e^{\lambda t}\ \ \ \implies\ \ \ \ \lambda = \pm \sqrt{\strut b\,c}\]</span>
The <span class="math inline">\(\pm\)</span> is the interesting part here. If, say, <span class="math inline">\(b=1\)</span> and <span class="math inline">\(c=1\)</span>, there are two values for <span class="math inline">\(\lambda\)</span> that will be consistent with the differential equation: <span class="math inline">\(\lambda_1 = 1\)</span> and <span class="math inline">\(\lambda_2 = -1\)</span>. Either of these will produce a solution that satisfies the differential equation: <span class="math inline">\(x_1(t) = A e^{\lambda_1 t}\)</span> or <span class="math inline">\(x_2(t) = B e^{\lambda_2 t}\)</span>. So which of the two possibilities is it?</p>
<p>Since everything about the differential equation is linear, any linear combination of the two possibilities will also satisfy the equation. So we can conclude that <span class="math display">\[x(t) = A e^{\lambda_1 t} + B e^{\lambda_2 t}\ .\]</span></p>
<p>What are <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>? That depends on the initial condition. Evaluate both sides of the equation at <span class="math inline">\(t=0\)</span> to get <span class="math display">\[x(0) = A e^{\lambda_1 0}+ B e^{\lambda_2 t} = A + B\ .\]</span>
At this point, you need to look back at the original system of equations. There are two state variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> and therefore we need to specify two components of the initial condition. If <span class="math inline">\(x(0)\)</span> is interpreted as the initial <strong>position</strong>, then following the example of the pendulum we can look to the <strong>velocity</strong> <span class="math inline">\(\partial_t x\)</span> as the second component of the initial condition. From <span class="math inline">\(x(t)\)</span> we can easily calculate the velocity:
<span class="math display">\[\partial_t x(t) = \lambda_1 A e^{\lambda_1 t} + \lambda_2 B e^{\lambda_2 t}\ .\]</span> Again, evaluate this at <span class="math inline">\(t=0\)</span> to get a second equation for the initial condition the pair
<span class="math display">\[\begin{array}{c}\partial_t x(0)  =   \lambda_1 A  +  \lambda_2 B\\x(0)  = \ \ A \ \  + \ B\\\end{array}\ \ \ \ \implies\ \ \ \ 
 \left[\begin{array}{c}\lambda_1 \ \ \ \ \ \lambda_2\\1 \ \ \ \ \ \  1\end{array}\right] \left[\begin{array}{C}A\\ B\end{array}\right] = \left[\begin{array}{C}x(0)\\ \partial_t x(0)\end{array}\right] .\]</span>
From Block 5, we know how to solve such matrix equations. So, given the initial values <span class="math inline">\(x(0)\)</span> and <span class="math inline">\(\partial_t x(0)\)</span>, we can find an exact, quantitative solution to the differential equation.</p>
<div class="example">
<p><span id="exm:unlabeled-div-9" class="example"><strong>Example 52.1  </strong></span><span class="math inline">\(\ \)</span></p>
<p>Let’s look at the flow field, some trajectories and their time series for the system <span class="math display">\[\partial_t x = b y\\\partial_t y = c x\]</span> for <span class="math inline">\(b=1\)</span> and <span class="math inline">\(c=2\)</span>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bc-system"></span>
<img src="MOSAIC-Calculus_files/figure-html/bc-system-1.png" alt="Three trajectories from the system $$\begin{array}{c}\partial_t x = y\\\partial_t y = 2 x\end{array}$$" width="90%" />
<p class="caption">
Figure 52.1: Three trajectories from the system <span class="math display">\[\begin{array}{c}\partial_t x = y\\\partial_t y = 2 x\end{array}\]</span>
</p>
</div>
<p>Each of these trajectories starts out by heading toward the fixed point at (0,0). Then, each turns and heads away toward <span class="math inline">\(\pm \infty\)</span> from the fixed point,</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bc-system-ts"></span>
<img src="MOSAIC-Calculus_files/figure-html/bc-system-ts-1.png" alt="The time series $x(t)$ for the three different trajectories in Figure \@ref(fig:bc-system)." width="90%" />
<p class="caption">
Figure 52.2: The time series <span class="math inline">\(x(t)\)</span> for the three different trajectories in Figure <a href="equilibria.html#fig:bc-system">52.1</a>.
</p>
</div>
<p>Each of the time series is similar, first showing exponential decay toward 0 then exponential growth toward <span class="math inline">\(\pm \infty\)</span>.</p>
<p>The initial conditions for the black and <span class="math inline">\(\color{magenta}{\text{magenta}}\)</span> trajectories are very similar. You can imagine a trajectory starting between those initial conditions that would go down the middle of the “trumpet.” This trajectory would be exponential decay toward 0, but would be hard to see since <span class="math inline">\(x=0, y=0\)</span> is an unstable fixed point (a saddle).</p>
<p>The initial condition for the black trajectory is <span class="math inline">\(x(0)=0.72\)</span> and <span class="math inline">\(y(0)=\partial_t x(0) = -1\)</span>, while for the <span class="math inline">\(\color{magenta}{\text{magenta}}\)</span> trajectory it is <span class="math inline">\(x(0)=0.70\)</span> and <span class="math inline">\(y(0)=\partial x(0) = -1\)</span>. Let’s find each trajectory as a separate linear combination <span class="math inline">\(A e^{\lambda_1 t} + B e^{\lambda_2 t}\)</span>. The equations to solve are <span class="math display">\[\left[\begin{array}{c}1 \ \ \ \ 1\\\lambda_1 \ \  \lambda_2\end{array}\right] \left[\begin{array}{c}A\\ B\end{array}\right] = \left[\begin{array}{c}x(0)\\ \partial_t x(0)\end{array}\right] .\]</span></p>
<p>By plugging in the parameters <span class="math inline">\(a=0\)</span>, <span class="math inline">\(b=1\)</span>, <span class="math inline">\(c=2\)</span>, <span class="math inline">\(d=0\)</span> in the dynamical functions, we find that <span class="math display">\[\lambda = \pm \sqrt{\strut 2} \approx \pm 1.4142 \ .\]</span> Therefore, we solve
<span class="math display">\[\left[\begin{array}{c}1.4142 \ \ \  -1.4142\\1 \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \   1\end{array}\right] \left[\begin{array}{c}A\\ B\end{array}\right] = \left[\begin{array}{c}\partial_t\,x(0)\\x(0)\end{array}\right] .\]</span></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="equilibria.html#cb47-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">rbind</span>(<span class="fl">1.4142</span>, <span class="dv">1</span>), <span class="fu">rbind</span>(<span class="sc">-</span><span class="fl">1.4142</span>,<span class="dv">1</span>))</span>
<span id="cb47-2"><a href="equilibria.html#cb47-2" aria-hidden="true" tabindex="-1"></a>b_black <span class="ot">=</span> <span class="fu">rbind</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="fl">0.72</span>)</span>
<span id="cb47-3"><a href="equilibria.html#cb47-3" aria-hidden="true" tabindex="-1"></a>b_magenta <span class="ot">=</span> <span class="fu">rbind</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="fl">0.70</span>)</span>
<span id="cb47-4"><a href="equilibria.html#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qr.solve</span>(M, b_black)</span></code></pre></div>
<pre><code>##             [,1]
## [1,] 0.006443219
## [2,] 0.713556781</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="equilibria.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qr.solve</span>(M, b_magenta)</span></code></pre></div>
<pre><code>##              [,1]
## [1,] -0.003556781
## [2,]  0.703556781</code></pre>
<p>The two trajectories are therefore
<span class="math display">\[x_\text{black}(t) = 0.0064 e^{1.4142 t} + 0.7136 e^{-1.4142}\\
\color{magenta}{x_\text{magenta}(t)} = -0.00356 e^{1.4142 t} + 0.70356 e^{-1.4142 t}\]</span>
For both trajectories, the initial amplitude of the decaying exponential is much larger than for the growing exponential. That’s why the time series decay toward zero initially. But as <span class="math inline">\(t\)</span> grows, the exponential growth become much more important. For the black trajectory, the exponential growth has a positive coefficient, so the growth is toward <span class="math inline">\(\infty\)</span>. But for the <span class="math inline">\(\color{magenta}{\text{magenta}}\)</span> trajectory, the exponential growth as a negative coefficient, thus that trajectory grows toward <span class="math inline">\(-\infty\)</span>.</p>
</div>
<p>The method we used to solve the simplified problem also works for the original problem
<span class="math display">\[\begin{array}{c}\partial_t x  = ax  +  b y \\ \partial_t y = c x +  dy\end{array}\ .\]</span></p>
<p>Step 1: Differentiate with respect to <span class="math inline">\(t\)</span> both sides of the top equation, giving</p>
<p><span class="math display">\[\begin{array}{c}\partial_{tt} x  =   a\, \partial_t x  +  b\, \partial_t y\\ \  \ \ \partial_t y =  c x \ \ \ \ \ \ \ +  dy\ \ \ \ \ \ \ \ \end{array}\ .\]</span>
Step 2: Use the second equation to substitute for <span class="math inline">\(\partial_t\, y\)</span> in the top equation, giving
<span class="math display">\[\partial_{tt} x = a \partial_t x + b\left(\strut c x + dy\right) = a\, \partial_t x + b\, c\, x + b\, d\, y\]</span>
Step 3: One more substitution. From the original top equation, we know <span class="math display">\[y = \frac{\partial_t x - a x}{b}\ .\]</span>
Plug this in for <span class="math inline">\(y\)</span> in the result from Step 2, giving
<span class="math display">\[\partial_{tt} x = a\, \partial_t x + b\, c\, x + b\, d\, \frac{\partial_t x - a x}{b} = \left(\strut a + d\right)\ \partial_t x + \left(\strut b c - a d\right)\]</span>
Step 4: Use the ansatz <span class="math inline">\(x(t) = e^{\lambda t}\)</span>. This produces
<span class="math display">\[\lambda^2 e^{\lambda t}= (a + d) \lambda e^{\lambda t}+ \left(\strut bc - ad\right)e^{\lambda t} \ \ \ \implies\ \ \ \lambda^2 = (a + d) \lambda + \left(\strut bc - ad\right)\]</span> which can be solved for <span class="math inline">\(\lambda\)</span>:
<span class="math display">\[\lambda = \left(a + d\right) \pm \sqrt{\left(a - d\right)^2 + 4 b c}\]</span>
Again, the <span class="math inline">\(\pm\)</span> is the interesting bit here. There are two simple solutions that satisfy the differential equation: <span class="math inline">\(x_1(t) = e^{\lambda_1 t}\)</span> and <span class="math inline">\(x_2(t) = e^{\lambda_2 t}\)</span>. In addition, any linear combination <span class="math inline">\(A e^{\lambda_ t} + B e^{\lambda_2 t}\)</span> of these simple solutions will satisfy the differential equations. Once we know <span class="math inline">\(\lambda_1\)</span> and <span class="math inline">\(\lambda_2\)</span>, the situation is identical to the simplified version. Again, knowing the initial condition <span class="math inline">\(x(0)\)</span> and <span class="math inline">\(\partial_t x(0)\)</span> allows us to find the coefficients in the linear combination by solving the matrix equation <span class="math display">\[\left[\begin{array}{c}1 \ \ \ \ \ 1\\\lambda_1 \ \ \  \lambda_2\end{array}\right] \left[\begin{array}{C}A\\ B\end{array}\right] = \left[\begin{array}{C}x(0)\\ \partial_t x(0)\end{array}\right] .\]</span></p>
<p>MAYBE SHOW THAT the vectors and time constants can be calculated using <code>eigen()</code>?</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modeling-dynamics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="eigenvalues.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dtkaplan/MOSAIC-Calculus/shared/B6-equilibria.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/dtkaplan/MOSAIC-Calculus/shared/B6-equilibria.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
