# Projection

## The residual vector



## Finding the target with QR 

Start with the very simple example of the identity matrix and reaching a target with that.

Show that the vectors in the identity matrix are mutually orthogonal.

Show that we can find a mutually orthogonal basis set for any matrix.


## Categorical inputs

Why a categorical variable corresponds to a set of indicator vectors. Why it wouldn't work to assign numbers 1,2,3,... to the categories (because that would presume that the second category is mathematical between the first and third).

Refer back to the data frame `mtcars` [BUT THIS IS ALL NUMERIC, SO NOT A GOOD SOURCE FOR CATEGORICAL EXAMPLES] displayed on a previous page. Describe how `model.matrix()` used the data to create the right-most vector in the model matrix.

## Exercises

`r insert_calcZ_exercise("XX.XX", "wniqMc", "Exercises/panda-begin-shoe.Rmd")`

`r insert_calcZ_exercise("XX.XX", "yeY17y", "Exercises/kangaroo-light-bowl.Rmd")`


`r insert_calcZ_exercise("XX.XX", "p209w8", "Exercises/beech-build-shirt.Rmd")`


`r insert_calcZ_exercise("XX.XX", "dvWdE7", "Exercises/puppy-dream-spoon.Rmd")`


a. Calculate the angle between two vectors
    i. arithmetically, using dot product
    ii. graphically, using protractor
b. Find a nonzero vector orthogonal to a given vector
c. Calculate the projection of a vector onto another vector
    i. arithmetically with dot product
    ii. graphically
d. Decompose a vector into a residual and a component directed along a second vector
    i. graphically
    ii. arithmetically
