---
id: "lamb-lead-gloves"
created: "Fri Jan 28 11:10:19 2022"
global_id: "83fMSu"
---

This exercise explores the dynamics of the grazing cows example using the interactive app in Figure \@ref(fig:cow-app).
In the following, we'll define a "well-fed cow" as a cow who eats at least 90% of what she would eat in ideal circumstances. A "starving" cow eats at most 50% of what she would eat in ideal circumstances. `r mark(6340)`

```{r cow4, echo=FALSE}
askMC(
  "Add one cow to the field. Judging from the net dynamics, what will be her condition?",
  "+well-fed+",
  "starving",
  "in between",
  random_answer_order = FALSE
)
```

```{r cow5, echo=FALSE}
explain <- "Is there a fixed point of the dynamics at 7 tons? No."
askMC(
  "Graze a total of ten cows in the field. These will reduce the biomass carrying capacity. What is that capacity with ten cows?",
  "1.2 tons/day" = "This is the fastest daily growth possible in the field.",
  "7 tons" =  explain,
  "7 tons/day" = "Wrong in a couple of ways.",
  "12 tons" = "This is the biomass that leads to the fastest growth, but it is still growth, not a fixed point.",
  "+22 tons+",
  "22 tons/day" = "Wrong dimensions.",
  random_answer_order = FALSE
)
```

```{r cow6, echo=FALSE}
askMC(
  "Seeing your cows and the grass thrive, you gradually add more and more to the field. What's the largest number of cows you can have in the field and still have well fed cows?",
  15, 19, "+22+", 24,
  random_answer_order = TRUE
)
```

```{r cow7, echo=FALSE}
etude2::etudeEssay(
  "We like sustainable systems to be robust against disturbances. For instance, there might be a week of cloudy weather that reduces grass growth by half. Explain why or why not the situation with 22 cows is robust." `r mark(6345)`
)
```

```{r cow8, echo=FALSE}
askMC(
  "Soon after the disruption caused by the week of cloudy weather, the field again reaches a stable fixed point. What's the biomass at this fixed point? Assume: you are still in the 22 cow scenerio.",
  "+less than 2 tons+",
  "6 tons",
  "12 tons",
  "greater than 12 tons",
  random_answer_order = FALSE
)
```

```{r cow9, echo=FALSE}
askMC(
  "After the disruption has passed and the system has again reached equilibrium, what will be the state of the 22 cows in the field?",
  "well-fed",
  "+starving+",
  "in between",
  random_answer_order = FALSE
)
```

```{r cow10, echo=FALSE}
askMC(
  "Seeing the state of your 22 cows, you decide that you need to decrease the herd size to a level where the cows were well fed: 20 cows. What stable biomass fixed point will the system reach?",
  "+3 tons+",
  "12 tons",
  "18 tons",
  "25 tons",
  random_answer_order = FALSE
)
```

```{r cow11, echo=FALSE}
askMC(
  "You're going to reduce the herd size still more to get things back to a healthy, stable equilibrium with well-fed cows. What's the largest herd size that will accomplish this?",
  5, 12, 15,  "+17+", 18, random_answer_order = FALSE
)
```

```{r cow12, echo=FALSE}
askMC(
  "At a herd size of 15 cows, about how many days will it take to get back (look at your end biomass for 20 cows) to a point where the cows are well fed? (Hint: How much will the biomass increase each day? The consumption curves starts to flatten out when the cows are well fed.)",
  "about 2 days",
  "about 5 days",
  "about 10 days",
  "+about 20 days+",
  random_answer_order = FALSE
)
```

```{r cow13, echo=FALSE}
askMC(
  "Like the previous question, but with 2 more cows. At a herd size of 17 cows, about how many days will it take to get back (look at your end biomass for 20 cows) to a point where the cows are well fed?",
  "about 10 days",
  "about 20 days",
  "about 30 days",
  "+about 100 days+" = "It takes a long time to get through the 'waist' in the net dynamics where the biomass is around 3 tons but the net growth is only about 0.01 ton per day.",
  random_answer_order = FALSE
)
```


